### ISSUE TITLE
Test-kitchen support

### ISSUE THREAD

**Issue by josephholsten** [edelight/chef-mongodb#114]
To get ourselves a safety net, we need automated testing for this cookbook. [Test-kitchen](https://github.com/opscode/test-kitchen) has the most momentum behind it today, and what it lacks in multi-node testing it mostly makes up for in tooling and support.

If we discover that we need multi-node support before it gets added to tk, we should consider [chef-workflow](https://github.com/chef-workflow/chef-workflow).

**Comment by josephholsten** [comment]
I vaguely remember someone mentioning a preference to minitest over bats, but I only have experience with bats and couldn't find any examples of test-kitchen + minitest use. I'll happily convert to minitest if someone points me at an example.

**Comment by jamesonjlee** [comment]
I liked mini-test more because I was told it was able to introspect the node variables.  Here is riak's minitest https://github.com/basho/riak-chef-cookbook/pull/66

a possible way to do multi-node setup with tk.  Looks like it basically spins up all nodes and wait for everything to converge and then runs a (integration) test.
https://github.com/bryanwb/tk-demo

**Comment by josephholsten** [comment]
Awesome! I'll review and update the patch.

**Comment by josephholsten** [comment]
BTW: I'm using opscode's [current recommendation](https://github.com/opscode/test-kitchen/pull/115) of a [provisioner-less base box](https://github.com/opscode/bento) along with the [vagrant-omnibus](https://github.com/schisamo/vagrant-omnibus) to install chef before the converge phase. This makes it more identical to a standard bootstrap approach.

If we start having issues supporting legacy chef installs, it may make sense to have separate boxes for say chef-10 and chef-11 clients. But as the title of this PR implies, I'm just trying to get something minimal in place.

**Comment by jamesonjlee** [comment]
yes.

**Comment by josephholsten** [comment]
Oooh, I heard multi-node was in the works. Very nice.
