### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by jamesonjlee** [edelight/chef-mongodb#117]
following up to #114 and #115 
1. The tests should be more than just "is it on?"
2. We should have test for all the other default setups this cookbook supports

**Comment by josephholsten** [comment]
#208 is working on tests for default cookbooks. But really this ticket needs to be more specific.

Anything in particular you want to check beyond "is it on?"

**Comment by josephholsten** [comment]
@jamesonjlee unless you've got specific things which need testing, I think this is safe to close
