### ISSUE TITLE
Recipe compile error in default.rb?

### ISSUE THREAD

**Issue by LiamK** [edelight/chef-mongodb#118]
Hi --
I'm new to Mongo and Chef, so this may not be an issue with chef-mongodb, but...
I just (as in a few minutes ago) was trying to use this (I think the HEAD) and got the error below.  Previously, I had been trying to use 0.11.0 which didn't work due to the error fixed in revision 9049dd.  As I said, I could be doing something wrong in how I have it configured.  Any help appreciated!
# 

Recipe Compile Error in /srv/chef/file_store/cookbooks/bti_mongo/recipes/default.rb
# 

Net::HTTPServerException

---

400 "Bad Request"

Cookbook Trace:

---

  /srv/chef/file_store/cookbooks/mongodb/definitions/mongodb.rb:164:in `block in from_file'
  /srv/chef/file_store/cookbooks/mongodb/recipes/replicaset.rb:24:in`from_file'
  /srv/chef/file_store/cookbooks/bti_mongo/recipes/default.rb:11:in `from_file'

Relevant File Content:

---

/srv/chef/file_store/cookbooks/mongodb/definitions/mongodb.rb:

157:        ignore_failure true
158:      end
159:    end
160:  
161:    # replicaset
162:    if !replicaset_name.nil? && node['mongodb']['auto_configure']['replicaset']
163:      rs_nodes = search(
164>>       :node,
165:        "mongodb_cluster_name:#{replicaset['mongodb']['cluster_name']} AND \
166:         recipes:mongodb\:\:replicaset AND \
167:         mongodb_shard_name:#{replicaset['mongodb']['shard_name']} AND \
168:         chef_environment:#{replicaset.chef_environment}"
169:      )
170:  
171:      ruby_block "config_replicaset" do
172:        block do
173:          if not replicaset.nil?

**Comment by jamesonjlee** [comment]
are you running with chef-server or chef-solo?

**Comment by josephholsten** [comment]
Hmm, maybe we should wrap this in a block to catch the error and give a better explanation? And possibly use chef-solo-search? We'll need chef solo search to test this in test-kitchen today (until chef-zero or server support comes out).

**Comment by LiamK** [comment]
Jameson,

I'm using the OpsCode hosted option -- although there is a message that
seems to indicate I'm not, which is confusing.
Please see my message below that I posted to the chef list.
I feel like I'm so close to getting it all to work!
Thanks in advance for your help.

Liam

On 05/29/2013 03:22 PM, Jameson wrote:

> are you running with chef-server or chef-solo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/edelight/chef-mongodb/issues/118#issuecomment-18650274.
> 
> Okay, I'm almost there!
> My goal is to have 3 mongo servers set up in a replicaset. I'm
> experimenting using VirtualBox with opscode-ubuntu-1204 vm
> (workstation is also Ubuntu 12.04).
> Below is the code from the Vagrantfile.  I _think_ that's what I
> want.  (I assign different vm.hostname and ip address and
> chef.node_name to each of the three servers.)
> Mongo is contained in a cookbook wrapper called bti_mongo.
> Mongo cookbook is retrieved via Berkshelf: cookbook 'mongodb', ">=
> 0.12.0", :git => 'git://github.com/edelight/chef-mongodb.git', branch:
> "9049ddde9fb6017321c1c9700228add78d2cc44d"
> (I tried several versions after discovering the bug introduced by
> change from Chef 10 to 11.  I think this is the one immediately after
> that change, but I had the same issue with the repo HEAD.)
> 
> I've just been creating and configuring the nodes with the OpsCode
> management site.  There is a node named "mongo1" with the bti_mongo
> recipe.
> 
> Anyway, I'm not clear on whether this is a bug in the mongo recipe, or
> perhaps due to some error I've made in setting things up.
> 
> Any help would be appreciated.
> 
> Liam
> 
> ---
> 
> Vagrantfile:
> 
> > Vagrant.configure("2") do |config|
> >   config.vm.provision :shell, :inline => "echo Hello"
> > 
> >   config.vm.define :mongo1 do |m|
> >     m.vm.box = "opscode-ubuntu-1204"
> >     m.vm.hostname = "mongo1"
> >     m.vm.network :private_network, ip: "10.10.10.71"
> >     m.vm.provision :chef_client do |chef|
> >       chef.node_name = "mongo1"
> >       chef.chef_server_url = "https://api.opscode.com/organizations/bti"
> >       chef.validation_key_path = ".chef/bti-validator.pem"
> >       chef.validation_client_name = "bti-validator"
> >     end
> >   end
> > <snip>
> 
> Starting vm:
> 
> > liam@gavilan$ vagrant up mongo1
> > Bringing machine 'mongo1' up with 'virtualbox' provider...
> > [mongo1] Setting the name of the VM...
> > [mongo1] Clearing any previously set forwarded ports...
> > [mongo1] Creating shared folders metadata...
> > [mongo1] Clearing any previously set network interfaces...
> > [mongo1] Preparing network interfaces based on configuration...
> > [mongo1] Forwarding ports...
> > [mongo1] -- 22 => 2222 (adapter 1)
> > [mongo1] Booting VM...
> > [mongo1] Waiting for VM to boot. This can take a few minutes.
> > [mongo1] VM booted and ready for use!
> > [mongo1] Setting hostname...
> > [mongo1] Configuring and enabling network interfaces...
> > [mongo1] Mounting shared folders...
> > [mongo1] -- /vagrant
> > [mongo1] Running provisioner: shell...
> > [mongo1] Running: inline script
> > stdin: is not a tty
> > Hello
> > [mongo1] Running provisioner: chef_client...
> > Creating folder to hold client key...
> > Uploading chef client validation key...
> > Generating chef JSON and uploading...
> > [mongo1] Warning: Chef solo run list is empty. This may not be what
> > you want.
> > Running chef-client...
> > stdin: is not a tty
> > [2013-05-30T07:05:03+00:00] INFO: **\* Chef 11.4.4 ***
> > [2013-05-30T07:05:03+00:00] INFO: [inet6] no default interface,
> > picking the first ipaddress
> > [2013-05-30T07:05:03+00:00] INFO: ipaddress and ip6address are set
> > from different interfaces (eth0 & eth1), macaddress has been set
> > using the ipaddress interface
> > [2013-05-30T07:05:04+00:00] INFO: Client key /etc/chef/client.pem is
> > not present - registering
> > [2013-05-30T07:05:12+00:00] INFO: Run List is [recipe[bti_mongo]]
> > [2013-05-30T07:05:12+00:00] INFO: Run List expands to [bti_mongo]
> > [2013-05-30T07:05:13+00:00] INFO: Starting Chef Run for mongo1
> > [2013-05-30T07:05:13+00:00] INFO: Running start handlers
> > [2013-05-30T07:05:13+00:00] INFO: Start handlers complete.
> > [2013-05-30T07:05:17+00:00] INFO: Loading cookbooks [apt, bti_mongo,
> > mongodb, yum]
> > [2013-05-30T07:05:20+00:00] INFO: Storing updated
> > cookbooks/mongodb/recipes/mongos.rb in the cache.
> > [2013-05-30T07:05:23+00:00] INFO: Storing updated
> > cookbooks/mongodb/recipes/configserver.rb in the cache.
> > [2013-05-30T07:05:24+00:00] INFO: Storing updated
> > cookbooks/mongodb/recipes/10gen_repo.rb in the cache.
> > [2013-05-30T07:05:25+00:00] INFO: Storing updated
> > cookbooks/mongodb/recipes/default.rb in the cache.
> > [2013-05-30T07:05:26+00:00] INFO: Storing updated
> > cookbooks/mongodb/recipes/shard.rb in the cache.
> > [2013-05-30T07:05:27+00:00] INFO: Storing updated
> > cookbooks/mongodb/recipes/replicaset.rb in the cache.
> > [2013-05-30T07:05:27+00:00] INFO: Storing updated
> > cookbooks/mongodb/definitions/mongodb.rb in the cache.
> > [2013-05-30T07:05:28+00:00] INFO: Storing updated
> > cookbooks/mongodb/libraries/mongodb.rb in the cache.
> > [2013-05-30T07:05:29+00:00] INFO: Storing updated
> > cookbooks/mongodb/attributes/default.rb in the cache.
> > [2013-05-30T07:05:30+00:00] INFO: Storing updated
> > cookbooks/mongodb/CHANGELOG in the cache.
> > [2013-05-30T07:05:31+00:00] INFO: Storing updated
> > cookbooks/mongodb/Makefile in the cache.
> > [2013-05-30T07:05:32+00:00] INFO: Storing updated
> > cookbooks/mongodb/.gitignore in the cache.
> > [2013-05-30T07:05:33+00:00] INFO: Storing updated
> > cookbooks/mongodb/NOTICE in the cache.
> > [2013-05-30T07:05:34+00:00] INFO: Storing updated
> > cookbooks/mongodb/README.md in the cache.
> > [2013-05-30T07:05:35+00:00] INFO: Storing updated
> > cookbooks/mongodb/LICENSE in the cache.
> > [2013-05-30T07:05:35+00:00] INFO: Storing updated
> > cookbooks/mongodb/metadata.rb in the cache.
> > [2013-05-30T07:05:36+00:00] INFO: Storing updated
> > cookbooks/bti_mongo/recipes/default.rb in the cache.
> > [2013-05-30T07:05:37+00:00] INFO: Storing updated
> > cookbooks/bti_mongo/CHANGELOG.md in the cache.
> > [2013-05-30T07:05:37+00:00] INFO: Storing updated
> > cookbooks/bti_mongo/README.md in the cache.
> > [2013-05-30T07:05:38+00:00] INFO: Storing updated
> > cookbooks/bti_mongo/metadata.rb in the cache.
> > [2013-05-30T07:05:39+00:00] INFO: Storing updated
> > cookbooks/apt/resources/preference.rb in the cache.
> > [2013-05-30T07:05:40+00:00] INFO: Storing updated
> > cookbooks/apt/resources/repository.rb in the cache.
> > [2013-05-30T07:05:44+00:00] INFO: Storing updated
> > cookbooks/apt/providers/preference.rb in the cache.
> > [2013-05-30T07:05:45+00:00] INFO: Storing updated
> > cookbooks/apt/providers/repository.rb in the cache.
> > [2013-05-30T07:05:45+00:00] INFO: Storing updated
> > cookbooks/apt/recipes/cacher-ng.rb in the cache.
> > [2013-05-30T07:05:46+00:00] INFO: Storing updated
> > cookbooks/apt/recipes/default.rb in the cache.
> > [2013-05-30T07:05:47+00:00] INFO: Storing updated
> > cookbooks/apt/recipes/cacher-client.rb in the cache.
> > [2013-05-30T07:05:47+00:00] INFO: Storing updated
> > cookbooks/apt/attributes/default.rb in the cache.
> > [2013-05-30T07:05:48+00:00] INFO: Storing updated
> > cookbooks/apt/Berksfile in the cache.
> > [2013-05-30T07:05:49+00:00] INFO: Storing updated
> > cookbooks/apt/TESTING.md in the cache.
> > [2013-05-30T07:05:50+00:00] INFO: Storing updated
> > cookbooks/apt/metadata.json in the cache.
> > [2013-05-30T07:05:51+00:00] INFO: Storing updated
> > cookbooks/apt/CONTRIBUTING in the cache.
> > [2013-05-30T07:05:51+00:00] INFO: Storing updated
> > cookbooks/apt/.gitignore in the cache.
> > [2013-05-30T07:05:52+00:00] INFO: Storing updated
> > cookbooks/apt/CHANGELOG.md in the cache.
> > [2013-05-30T07:05:53+00:00] INFO: Storing updated
> > cookbooks/apt/README.md in the cache.
> > [2013-05-30T07:05:54+00:00] INFO: Storing updated
> > cookbooks/apt/LICENSE in the cache.
> > [2013-05-30T07:05:54+00:00] INFO: Storing updated
> > cookbooks/apt/metadata.rb in the cache.
> > [2013-05-30T07:05:55+00:00] INFO: Storing updated
> > cookbooks/apt/.kitchen.yml in the cache.
> > [2013-05-30T07:05:56+00:00] INFO: Storing updated
> > cookbooks/yum/resources/key.rb in the cache.
> > [2013-05-30T07:05:57+00:00] INFO: Storing updated
> > cookbooks/yum/resources/repository.rb in the cache.
> > [2013-05-30T07:05:57+00:00] INFO: Storing updated
> > cookbooks/yum/providers/key.rb in the cache.
> > [2013-05-30T07:05:58+00:00] INFO: Storing updated
> > cookbooks/yum/providers/repository.rb in the cache.
> > [2013-05-30T07:06:04+00:00] INFO: Storing updated
> > cookbooks/yum/recipes/repoforge.rb in the cache.
> > [2013-05-30T07:06:05+00:00] INFO: Storing updated
> > cookbooks/yum/recipes/yum.rb in the cache.
> > [2013-05-30T07:06:06+00:00] INFO: Storing updated
> > cookbooks/yum/recipes/test.rb in the cache.
> > [2013-05-30T07:06:07+00:00] INFO: Storing updated
> > cookbooks/yum/recipes/ius.rb in the cache.
> > [2013-05-30T07:06:07+00:00] INFO: Storing updated
> > cookbooks/yum/recipes/default.rb in the cache.
> > [2013-05-30T07:06:08+00:00] INFO: Storing updated
> > cookbooks/yum/recipes/elrepo.rb in the cache.
> > [2013-05-30T07:06:09+00:00] INFO: Storing updated
> > cookbooks/yum/recipes/epel.rb in the cache.
> > [2013-05-30T07:06:10+00:00] INFO: Storing updated
> > cookbooks/yum/recipes/remi.rb in the cache.
> > [2013-05-30T07:06:10+00:00] INFO: Storing updated
> > cookbooks/yum/attributes/default.rb in the cache.
> > [2013-05-30T07:06:11+00:00] INFO: Storing updated
> > cookbooks/yum/attributes/elrepo.rb in the cache.
> > [2013-05-30T07:06:12+00:00] INFO: Storing updated
> > cookbooks/yum/attributes/epel.rb in the cache.
> > [2013-05-30T07:06:13+00:00] INFO: Storing updated
> > cookbooks/yum/attributes/remi.rb in the cache.
> > [2013-05-30T07:06:13+00:00] INFO: Storing updated
> > cookbooks/yum/Berksfile in the cache.
> > [2013-05-30T07:06:14+00:00] INFO: Storing updated
> > cookbooks/yum/metadata.json in the cache.
> > [2013-05-30T07:06:15+00:00] INFO: Storing updated
> > cookbooks/yum/CONTRIBUTING.md in the cache.
> > [2013-05-30T07:06:16+00:00] INFO: Storing updated
> > cookbooks/yum/.gitignore in the cache.
> > [2013-05-30T07:06:17+00:00] INFO: Storing updated
> > cookbooks/yum/CHANGELOG.md in the cache.
> > [2013-05-30T07:06:17+00:00] INFO: Storing updated
> > cookbooks/yum/README.md in the cache.
> > [2013-05-30T07:06:18+00:00] INFO: Storing updated
> > cookbooks/yum/LICENSE in the cache.
> > [2013-05-30T07:06:19+00:00] INFO: Storing updated
> > cookbooks/yum/metadata.rb in the cache.
> > [2013-05-30T07:06:20+00:00] INFO: Storing updated
> > cookbooks/yum/.kitchen.yml in the cache.
> > 
> > # 
> > 
> > Recipe Compile Error in
> > /srv/chef/file_store/cookbooks/bti_mongo/recipes/default.rb
> > 
> > # 
> > 
> > Net::HTTPServerException
> > 
> > ---
> > 
> > 400 "Bad Request"
> > 
> > Cookbook Trace:
> > 
> > ---
> > 
> > /srv/chef/file_store/cookbooks/mongodb/definitions/mongodb.rb:162:in
> > `block in from_file'
> >   /srv/chef/file_store/cookbooks/mongodb/recipes/replicaset.rb:24:in
> > `from_file'
> >   /srv/chef/file_store/cookbooks/bti_mongo/recipes/default.rb:11:in
> > `from_file'
> > 
> > Relevant File Content:
> > 
> > ---
> > 
> > /srv/chef/file_store/cookbooks/mongodb/definitions/mongodb.rb:
> > 
> > 155:        ignore_failure true
> > 156:      end
> > 157:    end
> > 158:  
> > 159:    # replicaset
> > 160:    if !replicaset_name.nil?
> > 161:      rs_nodes = search(
> > 162>>       :node,
> > 163:  
> > "mongodb_cluster_name:#{replicaset['mongodb']['cluster_name']} AND \
> > 164:         recipes:mongodb\:\:replicaset AND \
> > 165:  
> > mongodb_shard_name:#{replicaset['mongodb']['shard_name']} AND \
> > 166:         chef_environment:#{replicaset.chef_environment}"
> > 167:      )
> > 168:  
> > 169:      ruby_block "config_replicaset" do
> > 170:        block do
> > 171:          if not replicaset.nil?
> > 
> > [2013-05-30T07:06:20+00:00] ERROR: Running exception handlers
> > [2013-05-30T07:06:20+00:00] FATAL: Saving node information to
> > /srv/chef/file_store/failed-run-data.json
> > [2013-05-30T07:06:20+00:00] ERROR: Exception handlers complete
> > [2013-05-30T07:06:20+00:00] FATAL: Stacktrace dumped to
> > /srv/chef/file_store/chef-stacktrace.out
> > [2013-05-30T07:06:20+00:00] FATAL: Net::HTTPServerException: 400 "Bad
> > Request"
> > Chef never successfully completed! Any errors should be visible in the
> > output above. Please fix your recipes so that they properly complete.
> 
> ## 
> 
> Liam Kirsher
> PGP: http://liam.numenet.com/pgp/

## 

Liam Kirsher
PGP: http://liam.numenet.com/pgp/

**Comment by josephholsten** [comment]
um, github doesn't love your email. I'll try to dig into this, I'll let you know if I can make any sense out of it.

**Comment by josephholsten** [comment]
The error `Warning: Chef solo run list is empty. This may not be what you want.` may be an upstream bug, you look to correctly selecting chef-client in your Vagrantfile. I am, however, confused as to how this node has a run_list without you specifying it in the Vagrantfile.

**Comment by LiamK** [comment]
Hope this is better: http://pastebin.com/a9TiTPRA

I'm using the OpsCode hosted option, and am setting the run_list for the node via their management interface.

**Comment by josephholsten** [comment]
@LiamK Here seems to be the point of chef's contention: the mongodb cookbook finds replicas via a chef search of 

``` ruby
rs_nodes = search(
  :node,
  "mongodb_cluster_name:#{replicaset['mongodb']['cluster_name']} AND \
  recipes:mongodb\\:\\:replicaset AND \
  mongodb_shard_name:#{replicaset['mongodb']['shard_name']} AND \
  chef_environment:#{replicaset.chef_environment}"
)
```

I'm guessing that whatever you have as your `replicaset['mongodb']['cluster_name']` or `replicaset['mongodb']['shard_name']`, or `replicaset.chef_environment` is not playing nice with chef's lucene query language.

Have you explicitly set the `default[:mongodb][:cluster_name]` attribute on your nodes? It seems to [default to `nil`](https://github.com/edelight/chef-mongodb/blob/master/attributes/default.rb#L28), which I imagine does no play nice.

If you didn't, then this has identified a bug with our default attributes and error handling. If not, please let us know, and I'll try and dig in more.

**Comment by LiamK** [comment]
This is the bti_mongo/recipes/default.rb file:

> include_recipe 'mongodb::10gen_repo'
> include_recipe 'mongodb::replicaset'
> 
> node[:mongodb][:cluster_name] = 'bti'

I was a bit unclear if I need to set both cluster_name _and_ replicaset_name.
(Also, this is my first attempt at this so... )

**Comment by josephholsten** [comment]
All I feel I can say at the moment is $VULGARITY. 

Assuming you're using the default `replicaset['mongodb']['shard_name']`, and your node is in the `production` chef_environment, what happens when you run 

```
knife search node "mongodb_cluster_name:bti AND recipes:mongodb\\:\\:replicaset AND mongodb_shard_name:default AND chef_environment:production"
```

Can you dig into the attributes of the nodes you think should be in the cluster and verify they have the right attributes?

**Comment by josephholsten** [comment]
Also, because I'm frustrated at the error message from your situation, I entered an upstream ticket about the error handling of `search()` at http://tickets.opscode.com/browse/CHEF-4228

I doubt I'll have time to tackle it soon, but we might bug chef-dev about it.

**Comment by LiamK** [comment]
I did not set the shard_name.  (I have not checked with my client, but I think they were not sharding.)

> knife search node "mongodb_cluster_name:bti AND recipes:mongodb\:\:replicaset AND mongodb_shard_name:default AND chef_environment:production"
> 0 items found

Is the syntax in my default.rb file correct?
Um... also, I'm not sure I have chef_environment set to anything.  On the management site it looks like "_default".

**Comment by jamesonjlee** [comment]
as I last recall, unless you explicitly set one chef_environment will be `_default`

**Comment by josephholsten** [comment]
so it looks like the query our cookbook is trying to fire is equivalant to

```
knife search node "mongodb_cluster_name:bti AND recipes:mongodb\:\:replicaset AND mongodb_shard_name:default AND chef_environment:_default"
```

You won't really get a useful result unless you have all your nodes in the results of that, but it bothers me that you don't get an error or a 400 response when you made that earlier query. I hate to rag on hosted chef, but they are in a state of transition recently. Have you tried running the cookbook again? Maybe it was a transient solr issue?

**Comment by LiamK** [comment]
Okay... I've made some progress.  The problem was that the include_recipe was coming _before_ setting the cluster_name.  I moved that to attributes/default.rb 

> node.default[:mongodb][:cluster_name] = 'bti'

So, now at least it gets past that problem.
However, another issue has now appeared:

http://pastebin.com/VWyafCyP

**Comment by jamesonjlee** [comment]
looks like you are missing the ruby mongo gem, you may need to apply #110

**Comment by LiamK** [comment]
Thanks!  I added it to my recipe and it appears to have worked.  The
mongo server is running :-)
I'm getting a different error now:

> [2013-06-04T21:55:24+00:00] INFO: Processing service[mongodb] action
> start (mongodb::replicaset line 141)
> [2013-06-04T21:55:24+00:00] INFO: Processing
> ruby_block[config_replicaset] action nothing (mongodb::replicaset line
> 169)
> [2013-06-04T21:55:24+00:00] INFO: template[/etc/default/mongodb]
> sending restart action to service[mongodb](delayed)
> [2013-06-04T21:55:24+00:00] INFO: Processing service[mongodb] action
> restart (mongodb::replicaset line 141)
> [2013-06-04T21:55:36+00:00] INFO: service[mongodb] restarted
> [2013-06-04T21:55:36+00:00] INFO: service[mongodb] sending create
> action to ruby_block[config_replicaset](delayed)
> [2013-06-04T21:55:36+00:00] INFO: Processing
> ruby_block[config_replicaset] action create (mongodb::replicaset line 169)
> [2013-06-04T21:55:36+00:00] WARN: Cannot configure replicaset
> 'rs_default', no member nodes found
> [2013-06-04T21:55:36+00:00] INFO: ruby_block[config_replicaset] called
> [2013-06-04T21:55:36+00:00] ERROR: Running exception handlers
> [2013-06-04T21:55:37+00:00] FATAL: Saving node information to
> /srv/chef/file_store/failed-run-data.json
> [2013-06-04T21:55:37+00:00] ERROR: Exception handlers complete
> [2013-06-04T21:55:37+00:00] FATAL: Stacktrace dumped to
> /srv/chef/file_store/chef-stacktrace.out
> [2013-06-04T21:55:37+00:00] FATAL: Net::HTTPServerException: 403
> "Forbidden"
> Chef never successfully completed! Any errors should be visible in the
> output above. Please fix your recipes so that they properly complete.

(Full install log here: http://pastebin.com/gyCXPNkH )

Not surprisingly, the mongo.log file has lots of

> Wed Jun  5 03:01:39.966 [rsStart] replSet can't get
> local.system.replset config from self or any seed (EMPTYCONFIG)

Now, I'm not entirely surprised about "no member nodes found" since I
haven't started the other two yet.  This is something I'm not clear about.
I have set the default cluster_name in my wrapper
cookbooks/bti_mongo/attributes/default.rb file:

> node.default[:mongodb][:cluster_name] = 'bti'
> Is that correct?

I think I don't  have to set an explicit replicaset name --  just let it
default to rs_default, which appears to be what it's doing.
This may just be something I don't understand about Mongo.  Does one
node have to configure Mongo as the master and the others nodes as slaves?

Thanks for your help!

On 06/03/2013 02:27 AM, Jameson wrote:

> looks like you are missing the ruby mongo gem, you may need to apply
> #110 https://github.com/edelight/chef-mongodb/issues/110
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/edelight/chef-mongodb/issues/118#issuecomment-18830313.

## 

Liam Kirsher
PGP: http://liam.numenet.com/pgp/

**Comment by jamesonjlee** [comment]
it looks like 403 is being issued by chef, which from http://wiki.opscode.com/display/chef/Common+Errors is a chef configuration issue?

**Comment by LiamK** [comment]
Thanks for pointing that out.  Fixed.  Now it completes perfectly, with
only the

> WARN: Cannot configure replicaset 'rs_default', no member nodes found
> I now have all three mongo hosts configured and running. 
> However, they are not finding each other.  It looks like the attribute
> is getting set (to "bti")
> The code below indicates that a shard name is required.  I'm not
> familiar with Mongo, but I thought you could use replicaset without
> sharding.  Not correct?
> Using knife search works if I only put the cluster_name, but fails when
> I try to include the other stuff.
> 
> if !replicaset_name.nil?
>     rs_nodes = search(
>       :node,
>       "mongodb_cluster_name:#{replicaset['mongodb']['cluster_name']}AND \
> recipes:mongodb\:\:replicaset AND \
> mongodb_shard_name:#{replicaset['mongodb']['shard_name']}AND \
> chef_environment:#{replicaset.chef_environment}"
>     )
> 
> knife search node "mongodb_cluster_name:bti AND
> recipes:mongodb\:\:replicaset"
> 0 items found
> 
> knife search node "mongodb_cluster_name:bti"
> 3 items found
> 
> Node Name:   mongo2
> Environment: _default
> FQDN:        mongo2
> IP:          10.0.2.15
> Run List:    recipe[bti_mongo]
> Roles:  
> Recipes:     bti_mongo
> Platform:    ubuntu 12.04
> Tags:        
> 
> Node Name:   mongo3
> Environment: _default
> FQDN:        mongo3
> IP:          10.0.2.15
> Run List:    recipe[bti_mongo]
> Roles:  
> Recipes:     bti_mongo
> Platform:    ubuntu 12.04
> Tags:        
> 
> Node Name:   mongo1
> Environment: _default
> FQDN:        mongo1
> IP:          10.0.2.15
> Run List:    recipe[bti_mongo]
> Roles:  
> Recipes:     bti_mongo
> Platform:    ubuntu 12.04
> Tags:     

I'm going to make a wild guess -- could this be due to using a cookbook
wrapper design?

Liam

On 06/05/2013 03:46 AM, Jameson wrote:

> it looks like 403 is being issued by chef, which from
> http://wiki.opscode.com/display/chef/Common+Errors is a chef
> configuration issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/edelight/chef-mongodb/issues/118#issuecomment-18968180.

## 

Liam Kirsher
PGP: http://liam.numenet.com/pgp/

**Comment by jamesonjlee** [comment]
you shouldn't need to shard to create a replicaset.

**Comment by LiamK** [comment]
Jameson,

Well, good news.

I narrowed it down to the following.  The search for nodes is:
"mongodb_cluster_name:bti AND        recipes:mongodb\:\:replicaset
AND        mongodb_shard_name:default AND        chef_environment:_default"

That is failing because recipes:mongodb::replicaset is not true.
This /may/ be because of how I'm using mongodb cookbook: it's in a
wrapper cookbook, bti_mongo.
Could that account for it not being found in the recipes?

In my metadata.rb file I have
depends         'mongodb', ">= 0.12.0"

In cookbooks/bti_mongo/recipes/default.rb
  include_recipe 'mongodb::10gen_repo'
  include_recipe 'mongodb::replicaset'

I have tried adding recipe[mongodb::replicaset] to the run_list,
directly.  This appears to have had the desired result!  Yay!  I finally
have a working replicaset.

BTW, I'm wanting to put the data on an automatically mounted EBS volume.
I found one example of this, which isn't quite working for me.  If you
can point me at an example that does this (I'm sure it's a common
design) I'd much appreciate it.

Thanks!

Liam

On 06/06/2013 02:09 AM, Jameson wrote:

> you shouldn't need to shard to create a replicaset.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/edelight/chef-mongodb/issues/118#issuecomment-19033143.

## 

Liam Kirsher
PGP: http://liam.numenet.com/pgp/

**Comment by jamesonjlee** [comment]
there was/is a pull request that mentioned mounting EBS Raid automatically with mongo.

I am sure there is a EBS mounting cookbook somewhere that you can use to achieve the same goal.

But yes, I was going to say you will need to pull the recipes in directly, the cookbook has some stuff tossed around that you must be running certain recipes/definitions directly from those recipes.

**Comment by josephholsten** [comment]
@LiamK is this issue resolved?

**Comment by josephholsten** [comment]
reviewing this full thread, it seems like the bugs mentioned in this ticket are resolved.

**Comment by josephholsten** [comment]
@jamesonjlee seems like this can be closed.
