### ISSUE TITLE
Test mongodb::replicaset

### ISSUE THREAD

**Issue by josephholsten** [edelight/chef-mongodb#122]
Requires [chef-solo-search](https://github.com/edelight/chef-solo-search) to fake out the results of [definitions/mongodb.rb:163](https://github.com/edelight/chef-mongodb/blob/master/definitions/mongodb.rb#L163):

``` ruby
    rs_nodes = search(
      :node,
      "mongodb_cluster_name:#{replicaset['mongodb']['cluster_name']} AND \
       recipes:mongodb\\:\\:replicaset AND \
       mongodb_shard_name:#{replicaset['mongodb']['shard_name']} AND \
       chef_environment:#{replicaset.chef_environment}"
    )
```

**Comment by robmoore** [comment]
@josephholsten Thanks!

**Comment by robmoore** [comment]
@josephholsten I'd like to test this but need some help getting started. Are there any steps you could provide? Specifically, I'm not sure how to utilize chef-solo-search. It seems like I'd need a recipe to run but can't find any in the cookbook.

**Comment by josephholsten** [comment]
I'm spiking an example for using the `mongodb::mongos` cookbook now. I'll point you at it once I've got it working.

**Comment by josephholsten** [comment]
ugh, still no immediately relevant progress. #221 actually gives me a place where I can start touching this stuff tho.

**Comment by wolf31o2** [comment]
Using `chef-solo-search` means providing a data bag with the nodes. Again, not the best way to go about it. Removing the requirement for search, entirely, is definitely the way to go. Roles/JSON, then data bag, then search, please.

**Comment by josephholsten** [comment]
Moved to https://github.com/chef-brigade/mongodb-cookbook/issues/79
