### ISSUE TITLE
Replicaset configuration 

### ISSUE THREAD

**Issue by jgerry** [edelight/chef-mongodb#124]
I'm having some issues configuring a replicaset and had a few questions.

The general problem is this:
- ruby_block[config_replicaset] action create
  xxx.xxxxx.biz [2013-06-03T19:13:58+00:00] WARN: Cannot configure replicaset 'rep1', no member nodes found

I get this on every node I try to start. Related to the search for other nodes, which don't exist yet? I seem to have the same problem even when I have other nodes up. Is there any way to override the search and just set members via attribute?

EDIT: This is using Chef Server 11 and Chef 11.4.4

**Comment by jamesonjlee** [comment]
not at this moment.  you issue is probably related to stuff in #118

**Comment by tphummel** [comment]
one option I found to avoid the search() issue with chef-solo is to do: 

```
set['mongodb']['auto_configure']['replicaset'] = false
```

and do the rs config on the nodes manually

**Comment by josephholsten** [comment]
yeah, we really need to support manually setting the replicaset members via node attribute and parameter to `mongodb_instance`.  Technically, your bug is related to search, but I'd rather get a the low-tech hammer working first, then fix the fancy search stuff.

**Comment by josephholsten** [comment]
Seems like I'll actually get the fancy stuff first, see #215 

@jamesonjlee this seems safe to close
