### ISSUE TITLE
Prevent mongodb from start before configuration stage.

### ISSUE THREAD

**Issue by nikolaiderzhak** [edelight/chef-mongodb#127]
Start of mongod before configuration is useless when you change dbpath or/and logpath for example.
It will create prealloc\* journal files in default locations.
Also this is useless when we need arbiter with --nojournal option .

There are couple solutions here: http://stackoverflow.com/questions/12263244/how-do-i-install-mongodb-on-ubuntu-and-set-the-config-at-install-time for Ubuntu.

Also I believe next method will work: put mongodb config first then install OS mongodb package.

**Comment by jamesonjlee** [comment]
I plan to address this with the next batch of commits that will split up centos, redhat, fedora, ubuntu, debian configurations again.  Mainly we will prevent the initialization by using the system configuration files and setting the `ENABLE_MONGODB=no` and following the init files from there.

**Comment by josephholsten** [comment]
@jamesonjlee any ideas on how to do that idempotently? Perhaps you could only drop that config setting when the package is not installed? I'd hate to dig around in the package providers to make this work.

**Comment by jamesonjlee** [comment]
this technically works now, the larger issue is with the upstream packages not using the same flags.  If you see the dbconfig attributes I do all 3 variants that I have seen in the past.

**Comment by josephholsten** [comment]
@jamesonjlee seems like this is safe to close

**Comment by jamesonjlee** [comment]
- real follow up *
  for the debian family we need to setup /usr/sbin/policy-rc.d instead of doing the terrible amalgamation that I created.
