### ISSUE TITLE
mongos init.d script does not work (at least on the RHEL family)

### ISSUE THREAD

**Issue by astral303** [edelight/chef-mongodb#131]
When using the mongos recipe, the generated init.d script references the mongod binary everywhere, and also references a lock file in an empty DBPATH. 

It seems that mongos doesn't emit a lock file the way that mongod does, so the fallback is to search for the mongos process name. If anyone knows a better way to get a pid out of mongos --fork startup, please comment.

**Comment by msaffitz** [comment]
+1 It seems that the mongos recipe is completely broken due to this.

**Comment by jamesonjlee** [comment]
i believe mongos for this part is now fixed...
