### ISSUE TITLE
What :package_version is expected for example MongoDB version 2.4.4 ?

### ISSUE THREAD

**Issue by lancelakey** [edelight/chef-mongodb#135]
First, thanks for this cookbook.

With regards to: `mongodb[:package_version]` - Version of the MongoDB package to install, default is nil

Specifying a `:package_version` of "2.4.4" in an attributes file like so: `node.normal[:mongodb][:package_version] = "2.4.4"`

I get an error when I run the default recipe: "Version 2.4.4 of mongo-10gen-server not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)",

All the combinations I've tried of `mongo-10gen-server-2.4.4-mongodb_1.x86_64.rpm` from `http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/RPMS/` fail with that same error.

What am I expected to specify as the `:package_version` if I'm trying to install version 2.4.4 on CentOS 6.4?

**Comment by lefnire** [comment]
I only get this error if I don't include `"recipe[mongodb::10gen_repo]"` before `"recipe[mongodb::default]"` in the run-list, which I think is intended

``` json
{
  "name": "mongodb",
  "description": "Install MongoDB",
  "json_class": "Chef::Role",
  "default_attributes": {
  },
  "override_attributes": {
  },
  "chef_type": "role",
  "run_list": [
    "recipe[mongodb::10gen_repo]",
    "recipe[mongodb::default]"
  ],
  "env_run_lists": {
  }
}
```

**Comment by jamesonjlee** [comment]
this is a known problem, basically the cookbook doesn't support installing from distribution repos well.
It isn't intended that you have to do this, but right now a smooth install requries that "recipe[mongodb::10gen_repo]" before "recipe[mongodb::default]"

this is being fixed soon...

**Comment by jamesonjlee** [comment]
also, AFAIK CentOS doesn't have a native mongod package, so you _must_ install from 10gen.

**Comment by lefnire** [comment]
IIRC [you must](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/) as well for Debian / Ubuntu? A small requirement IMO, not a big deal

**Comment by lancelakey** [comment]
Thanks for the comment about `"recipe[mongodb::10gen_repo]"`. I see that in the Readme now but I missed that earlier. That was half of my problem.

The other half of my problem was the  `package_version`. I figured out if I want to install `2.4.4` then the `package_version` has to be `2.4.4-mongodb_1`. I never had to specify this funny looking version name when installing MongoDB manually because apt or yum would just install the latest version. However, since this recipe is specifying the version I had to use the exact version name from the repository which is `2.4.4-mongodb_1`.

Chef 11
CentOS 6.4
MongoDB 2.4.4

##### attributes/default.rb

``` ruby
node.normal[:mongodb][:package_version] = "2.4.4-mongodb_1"
```

##### recipes/default.rb

``` ruby
include_recipe "chef-mongodb::10gen_repo"
include_recipe "chef-mongodb::default"

service "mongod" do
  action :start
end
```

**Comment by jamesonjlee** [comment]
@lefnire not for Ubuntu at least, it has mongodb packages in various names.

**Comment by jamesonjlee** [comment]
if you don't set the package version the package resource should install whatever the latest one is available I think.

**Comment by lancelakey** [comment]
...and it does. Much simpler. Thanks.

When I saw `default[:mongodb][:package_version] = nil` I assumed that was bad and that meant I had to specify a `:package_version`
