### ISSUE TITLE
Could you be a little bit more caring about the versioning of the cookbook?

### ISSUE THREAD

**Issue by simonjohansson** [edelight/chef-mongodb#137]
First of all, thanks for a banging cookbook, we use it in production with great success.

Would you guys consider to be a bit more caring when it comes to the versioning/tagging of the cookbook? Its been on version 0.12 for quite a while now and there has been lots of commits since it was bumped.

We use berkshelf for our dependencies so its easily solvable for us by doing so
`cookbook "mongodb", git: "https://github.com/edelight/chef-mongodb.git", ref: "e56f80b599e05ff46039b09a0fa65d325c4ba46b"`

But it would be nicer to be able to take advantage of the awesomeness that comes with versioning(different versions in different chef environments etc), and it would surely help people that doesn't use berks/librarian.

**Comment by josephholsten** [comment]
@jamesonjlee it's a good point. I know you're ramping up for 1.0, but maybe an interim release would be in order? The current release is so broken as to be hardly worth calling 'stable'.

Do you have release access for http://community.opscode.com/cookbooks/mongodb?

**Comment by bplunkert** [comment]
I would respectfully like to second this request. We use version pinning (knife cookbook upload --freeze) and it's always a HUGE time-savings when standard practices are followed on versions -- odd numbers for development, even for releases. Then we can use --freeze safely for production releases. 

Nobody wants to have to knife cookbook download to figure out exactly what code is running :)

**Comment by tobami** [comment]
OK, is current master in an acceptable state for you to be tagged as 0.13?

**Comment by simonjohansson** [comment]
I think every commit on master should have its own tag and version-bump!

An easy way of doing this would be to development on a development branch, then every time when merging into master one would also bump version and add a tag. 
May I recomend git-flow[1]? Its a great tool for this kind of workflow, it even takes care of tagging for you, all one has to remember is to bump the version number in metadata and its really simple to use and integrates seamlessly into git and has completion for both bash and zsh. :)

[1] http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/

**Comment by tobami** [comment]
Ah, yeah, I heard about it. It looks a bit overkill in some cases, though I guess in this case it could improve the community-cookbook upload workflow...

**Comment by bplunkert** [comment]
I am sure branches and git-flow could help in this case. However, I'd be satisfied if I could just be sure that version X of this cookbook is always the same as version X of the same cookbook. 

Or, it could also be handled the same way most cookbooks are doing now, with even-numbered versions never being changed, but odd-numbered versions under active development.

**Comment by simonjohansson** [comment]
> Or, it could also be handled the same way most cookbooks are doing now, with even-numbered versions never being changed, but odd-numbered versions under active development.

With berks, it wont upload any changes to the chef-server if the version-number is the same, i.e if development is happening on version 1.3.3.7, I have uploaded a older 1.3.3.7 and I want to push the latest changes, berks will just ignore since 1.3.3.7 would already be in the chef-server. But then again, Im not sure I would like to upload development versions in the first place :)

**Comment by jamesonjlee** [comment]
i'm for moving versions up, but even if we move versions up someone has to push it to the community repo.

**Comment by josephholsten** [comment]
any chance @thekorn can add @jamesonjlee as a collaborator to http://community.opscode.com/cookbooks/mongodb?

**Comment by maikihde** [comment]
Can we expect 0.13 anytime soon? I just found out about this versioning Issue and would be interested, too.

**Comment by josephholsten** [comment]
@tobami I notice you've got contributor status on the community site. Are you comfortable pushing a release?

**Comment by simonjohansson** [comment]
Until 0.13 gets pushed to community site, can we create the 0.13 tag here on github? :)

**Comment by jamesonjlee** [comment]
0.13.0 tag on github.

**Comment by jamesonjlee** [comment]
@tobami any chance newer versions can be push to the community site?

**Comment by tehmaspc** [comment]
@tobami @jamesonjlee - yes please, can we update the OpsCode community site? We use Berkshelf which we have to explicitly tell to use this Git repo - but it creates more confusion. Would be great if you could bump the community version - mainly because there is a big issue with the current community version where it doesn't have the updated RHEL repo support - which totally blows. Would appreciate it if you can find the time to bump - or allow me to do it :)

Cheers,

**Comment by jamesonjlee** [comment]
hoping that @tobami and @thekorn can give me push rights to the community or something...

**Comment by tobami** [comment]
Sorry for taking so long. I have uploaded the latest tagged version, 0.13.3, hope everything works well now with berkshelf and cookbook versioning!

@thekorn should also be adding @jamesonjlee to the community cookbook so that he can push in the future
