### ISSUE TITLE
RFC: simplify daemon opt handling

### ISSUE THREAD

**Issue by josephholsten** [edelight/chef-mongodb#140]
For the next major release, I'd like to move all the options related to daemon or config file options into a single attribute hash: `node['opts']`, including: 
- _config_: path
- _port_: integer
- _bind_ip_: ip address
- _logpath_: path
- _syslog_: boolean
- _key_file_: path
- _fork_: boolean
- _auth_: boolean
- _dbpath_: path
- _journal_: boolean
- _rest_: boolean
- _smallfiles_: boolean
- _prealloc_: boolean
- _repl_set_: string
- _configsvr_: boolean
- _shardsvr_: boolean
- _configdb_: string

Ideally, this would be converted from key-value pairs into command line and config file compatible values:

``` ruby
# take a ruby-style key (lower snake case)  and convert to mongo-option-style (lower camel case) key
# Example:
#   flagify 'foo_bar_baz'
#   # => "fooBarBaz"
def flagify(key)
  segs = key.split('_')
  ret = []
  ret.push segs.shift
  segs.each {|seg| ret.push seg[0].upcase; ret.push seg[1..-1] }
  ret.join
end

# Take a hash of mongo options with ruby-style keys and convert to a list of mongo options which can be used either in a mongo config file or as command-line flags
# Example:
#   config_options_from_hash(
#     'bind_ip' => '127.0.0.1',
#     'key_file' => '/etc/mongodb.key'
#   )
#   # => ["bindIp=127.0.0.1", "keyFile=/etc/mongodb.key"]
def config_options_from_hash(hash)
  hash.map do |k,v|
    "%s=%s" % [flagify(k.to_s), v]
  end
end
```

This would allow the mongo definition to accept a single option hash, and allow it to be smarter about flag interactions (e.g. logpath and syslog are mutually exclusive).

Thus the command line flags could be built like:

``` erb
<% @daemon_ops.each do |opt| %>
DAEMON_OPTS="$DAEMON_OPTS --<%= opt %>"
<% end %>
```

And a config file could be built like:

``` erb
<% @daemon_ops.each do |opt| %>
<%= opt %>
<% end %>
```

**Comment by jamesonjlee** [comment]
I am in favor of a node attribute that holds a k-v pair for generating the configs/options, so I like this approach.

But we should move all possible configuration into mongodb.conf file, this will make upstream handling easier (for init) and only depends on mongo being able to parse the configuration file. (some cmd line options can not be passed though, e.g. --fork).  The configuration file also .ini style, so we don't have to worry about types.

I like the way DAEMON_OPTS is being built in this though.

If you want the version of this, I have one that is currently passing tests that will rebase over for LWRP stuff comes in: https://github.com/jamesonjlee/chef-mongodb/tree/attribute-config

**Comment by josephholsten** [comment]
I think this is effectively done
