### ISSUE TITLE
`ulimit -u` doesn't work when /bin/sh is dash

### ISSUE THREAD

**Issue by mkantor** [edelight/chef-mongodb#146]
The mongodb init script template has the shebang [`#!/bin/sh`](https://github.com/edelight/chef-mongodb/blob/8edc56873324d1c9aeefa93f61a89b92b83628a8/templates/default/mongodb.init.erb#L1). It also uses [`ulimit -u`](https://github.com/edelight/chef-mongodb/blob/8edc56873324d1c9aeefa93f61a89b92b83628a8/templates/default/mongodb.init.erb#L49), but [the `-u` option doesn't exist in dash](http://askubuntu.com/questions/97257/ulimit-u-gives-illegal-option-error-when-running-from-a-script-but-not-when-fro) (and possibly other shells). These days by default /bin/sh is linked to dash on [Ubuntu](https://wiki.ubuntu.com/DashAsBinSh) and [Debian](https://wiki.debian.org/DashAsBinSh) (and possibly other distributions), meaning that my chef run fails with the following ugly error unless I change my default shell to bash:

```
[2013-09-27T20:42:15+00:00] ERROR: service[mongodb] (mongodb::shard line 25) had an error: Expected process to exit with [0], but received '1'
---- Begin output of /etc/init.d/mongodb restart ----
STDOUT: ** Running mongodb (/usr/bin/mongod  --port 27017 --dbpath /var/lib/mongodb --logpath /var/log/mongodb/mongodb.log)
 * Restarting database mongodb
   ...fail!
STDERR: /etc/init.d/mongodb: 48: ulimit: Illegal option -u
---- End output of /etc/init.d/mongodb restart ----
Ran /etc/init.d/mongodb restart returned 1; ignore_failure is set, continuing

================================================================================
Error executing action `restart` on resource 'service[mongodb]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /etc/init.d/mongodb restart ----
STDOUT: ** Running mongodb (/usr/bin/mongod  --port 27017 --dbpath /var/lib/mongodb --logpath /var/log/mongodb/mongodb.log)
 * Restarting database mongodb
   ...fail!
STDERR: /etc/init.d/mongodb: 48: ulimit: Illegal option -u
---- End output of /etc/init.d/mongodb restart ----
Ran /etc/init.d/mongodb restart returned 1


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mongodb/recipes/shard.rb

 25: service "mongodb" do
 26:   supports :status => true, :restart => true
 27:   action [:disable, :stop]
 28: end
 29: 



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mongodb/recipes/shard.rb:25:in `from_file'

service("mongodb") do
  action [:disable, :stop]
  updated true
  supports {:status=>true, :restart=>true}
  ignore_failure true
  retries 0
  retry_delay 2
  service_name "mongodb"
  pattern "mongodb"
  startup_type :automatic
  cookbook_name "mongodb"
  recipe_name "shard"
end
```

**Comment by jamesonjlee** [comment]
oh dash, how I disliked it when ubuntu switched to you ffff, also when everyone really learned that... blah blah blah.

I am starting to think we need to include the ulimit/sysctl as a dependency.

**Comment by mkantor** [comment]
`ulimit` is a builtin shell command, unfortunately :unamused:.

**Comment by mkantor** [comment]
Although you could have a bash dependency and change the template to use `#!/bin/bash`.

**Comment by josephholsten** [comment]
Is there no /usr/bin/limit? I'd check but I'm on a train.

**Comment by jamesonjlee** [comment]
yes, templates being forced to be `#!/bin/bash` would be the correct way (since the script is a bash script not a shell script), and bash is a required install for debian (as I recall reading somewhere).

**Comment by jamesonjlee** [comment]
while I would love to be explicit, this is something we inherit directly from mongo (https://github.com/mongodb/mongo/blob/master/debian/init.d) so this should get raised up to them,

in the mean time the best course of action should be to alter the shell of the mongo user to be /bin/bash.

**Comment by mkantor** [comment]
@jamesonjlee [The upstream mongo init.d script](https://github.com/mongodb/mongo/blob/master/debian/init.d) doesn't contain any `ulimit` commands. Their script probably works identically under bash and dash.

**Comment by jamesonjlee** [comment]
ugh right...

**Comment by mkantor** [comment]
Is there a particular reason to configure ulimits in the init script instead of in the cookbook itself? We use [the official ulimit cookbook](http://community.opscode.com/cookbooks/ulimit) in the Chef recipe for one of our applications at work and it works well. Seems unnecessary to do it every time mongo is restarted anyway.

**Comment by jamesonjlee** [comment]
that was my intention, if you would like to open a PR with that integrated I will be happy to merge it in.

**Comment by josephholsten** [comment]
The reason the I limit cookbook wasn't used is that the init script was not originally using a mechanism to defer to pam to override the limits. This is the same reason it cannot be used with start-stop-daemon, or upstart, or systemd.

Ultimately, the way to play nice with the ulimit cookbook is to to use su, or some other tool that actively integrates with pam (login, sshd, and sudo are other examples).

I previously tried to make this cookbook play nice with the ulimit cookbook with less than great success. I'd love for it to work. But my last experience seemed to indicate that that could not work.

## If you're up for a challenge, I encourage you to prove me wrong. But let me know if you get stuck, I may be able to help dig you out of holes I fell into in the past. 

http://josephholsten.com

**Comment by mkantor** [comment]
I'm currently working on getting EBS snapshots/restores working on top of master (in a hopefully more workable way than [the Parse pull request](https://github.com/edelight/chef-mongodb/pull/96)), so I've been quite busy there. After that I might be able to experiment with alternative ulimit configurations; for now we're just setting our default shell to bash, which works but is not ideal.

@josephholsten Thanks for the background and the offer to help; I'll let you know if I end up trying to tackle this and get stuck anywhere. Don't expect it anytime soon, though.

**Comment by josephholsten** [comment]
lol, we could just add it to dash: http://git.kernel.org/cgit/utils/dash/dash.git/tree/src/miscbltin.c?id=46abc8c6d8a5e9a5712bdc1312c0b6960eec65a4#n361
