### ISSUE TITLE
Search and solr commit interval with Chef 11

### ISSUE THREAD

**Issue by twendt** [edelight/chef-mongodb#152]
On Chef 11 I have the issue that the searches sometimes do not work properly in this cookbook if, because solr has not rebuild the index fast enough. This causes missing servers in the search results. By default Cheff 11 rebuilds the index every 60 seconds.
My current solution is a fixed sleep before every search, but this could be made configurable by an attribute easily. Or is there any better solution?

**Comment by jamesonjlee** [comment]
we are planning on trimming down the search dependency, so hopefully we will be able to pare down the search better.

I don't think sleeping before a search is the best solution, from the sound of it though you might need to put chef into a bigger box?

**Comment by josephholsten** [comment]
I'd like to get our search thing isolated into its own bit like I did in https://github.com/elasticsearch/cookbook-elasticsearch/blob/master/libraries/search_for_nodes.rb

That way we could just have the list of nodes be in a node attribute or resource parameter.

@twendt I've typically handled this by having the first chef run be a bootstrap, so the correct config is applied on the second chef run.

Alternatively, we could just always add the current node to the discovered nodes and uniq the results. That's probably better than what I've been doing.

**Comment by twendt** [comment]
I was thinking about adding the current node as well, but this doesn't solve the issue as in our case we deploy the nodes of the replicaset one after the other and it is the previous node that is not found by the search. This can only be solved by waiting for it to appear. Since the chef-client cannot know which nodes have already been deployed it is only possible to wait for a certain time.
What might work could be doing a node.save and then keep trying until the current nodes appears in the search as well.

**Comment by jamesonjlee** [comment]
yes, I believe there are about 3 different PRs that goes at the search related issues, I would like search to be split out as much as possible mainly in style with #125

**Comment by josephholsten** [comment]
@twendt I had many discussions about this at the chef community summit. Chef search is just not the right hammer for this nail. I've begun investigating abstracting our search into a API that could support multiple backends, perhaps derived from heavy water's [discovery](https://github.com/hw-cookbooks/discovery). But the only way to really make you happy is to get your node discovery happening on another system, ideally [serf](http://www.serfdom.io), [etcd](https://github.com/coreos/etcd) or [zookeeper](http://zookeeper.apache.org).

I'm absolutely against a WONT-FIX resolution, but I can tell you that a proper solution won't be happening soon.

**Comment by josephholsten** [comment]
cf #215
