### ISSUE TITLE
Librarian-Chef on Windows chokes on certain file paths

### ISSUE THREAD

**Issue by WMeldon** [edelight/chef-mongodb#160]
Ran into a rather strange issue where I was getting EOENT ruby errors when trying to install this cookbook through Librarian-Chef on windows.  

I figured out that a 260 character path from this cookbook was the issue.

The issue was addressed by https://github.com/applicationsonline/librarian/issues/130 to an extent, but some paths, specifically this one:

```
/package/.kitchen/kitchen-vagrant/default-centos-64/.vagrant/machines/default/virtualbox
```

Can still cause the issue.  Not really a fixable problem but I figured this might help someone in the future.  My "workaround" was moving the project directory.

**Comment by jamesonjlee** [comment]
thanks for reporting, looks to be an upstream issue so I will close it.
