### ISSUE TITLE
Log File Not Properly Being Set

### ISSUE THREAD

**Issue by msaffitz** [edelight/chef-mongodb#172]
`node['mongodb']['type']` isn't a valid attribute, so https://github.com/edelight/chef-mongodb/blob/master/attributes/dbconfig.rb#L8 creates a log file named `/var/log/mongodb/.log`

**Comment by krukgit** [comment]
It's not really related but while you're changing logging related attributes it would be good to change 
`default['mognodb']['config']['logappend']` to  `default['mongodb']['config']['logappend']` in `attributes/dbconfig.rb`

--edit--
@msaffitz you're right, I didn't check the newest commit

**Comment by msaffitz** [comment]
@krukgit that was fixed in c02ceb657d5bd4c0d91b7c4f6e2eba2a11c32202

**Comment by jamesonjlee** [comment]
I knew i missed one.
