### ISSUE TITLE
Error executing action `enable` on resource 'service[shard]'

### ISSUE THREAD

**Issue by krukgit** [edelight/chef-mongodb#174]
I've been trying to set up sharding with replicasets on ubuntu 12.04 but I keep running into an error. I tried removing replicasets from the run_list but the error persists.

```
  * service[shard] action enable
================================================================================
Error executing action `enable` on resource 'service[shard]'
================================================================================


Chef::Exceptions::Exec
----------------------
/usr/sbin/update-rc.d shard defaults returned 1, expected 0


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb

145:   service name do
146:     supports :status => true, :restart => true
147:     action service_action
148:     service_notifies.each do |service_notify|
149:       notifies :run, service_notify
150:     end
151:     if !replicaset_name.nil? && node['mongodb']['auto_configure']['replicaset']
152:       notifies :create, "ruby_block[config_replicaset]"
153:     end
154:     if type == "mongos" && node['mongodb']['auto_configure']['sharding']



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:145:in `block in from_file'

service("shard") do
  params {:mongodb_type=>"shard", :action=>[:enable, :start], :bind_ip=>nil, :port=>27017, :logpath=>"/var/log/mongodb", :dbpath=>"/vol/mongodb", :configserver=>[], :replicaset=>nil, :enable_rest=>false, :smallfiles=>false, :notifies=>[], :name=>"shard"}
  action [:enable, :start]
  supports {:status=>true, :restart=>true}
  retries 0
  retry_delay 2
  service_name "shard"
  pattern "shard"
  startup_type :automatic
  cookbook_name "mongodb"
  recipe_name "shard"
end



[2013-11-22T04:17:52+00:00] ERROR: Running exception handlers
[2013-11-22T04:17:52+00:00] ERROR: Exception handlers complete
[2013-11-22T04:17:52+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 3 resources updated
[2013-11-22T04:17:52+00:00] ERROR: service[shard] (mongodb::shard line 145) had an error: Chef::Exceptions::Exec: /usr/sbin/update-rc.d shard defaults returned 1, expected 0
[2013-11-22T04:17:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

On the runs when mongo config file is being modified (including the first run) the restart action is executed and I receive additional error:

```
No such file or directory - /etc/init.d/shard restart
```

I also tried running `sudo /usr/sbin/update-rc.d shard defaults` manually and received `update-rc.d: /etc/init.d/shard: file does not exist`. For some reason update-rc doesn't cooperate well with upstart.

**Comment by krukgit** [comment]
Ok, I did some reading and it seems using update-rc doesn't make any sense with upstart services. For some reason Chef uses wrong provider for service management. Manually forcing it to use `Chef::Provider::Service::Upstart` solves the problem.

**Comment by jspiewak** [comment]
On ubuntu, /etc/init.d/mongodb is installed from the mongodb package as a link to /lib/init/upstart-job
Because the chef cookbook creates a separate service for shard, nothing is putting an /etc/init.d/shard link in place.

Overall, I am not sure why shard is being created as a separate service, and mongodb is still being left around. I would prefer there to just be a mongodb service that is a shard server.

**Comment by jamesonjlee** [comment]
as a note, right now the 0.14.X releases are for solidifying configurations/init scripts, and I believe it doesn't work well for sharding.

**Comment by jspiewak** [comment]
My team might be interested in helping to make things work well for sharding. What would be useful?

**Comment by josephholsten** [comment]
@jspiewak are you currently using this cookbook in a sharded mode? It would really be useful to define the requirements so maybe we could write tests and make sure we don't break anything in future.

**Comment by jspiewak** [comment]
We are in the process of converting from an old homegrown half-baked mongodb cookbook to this one.
We are the first team in the org that will be using it, and we will want to set up sharding.
We can start sketching out requirements and such.

Even before that though, what was the thinking behind creating the separate `shard` service? Should that be kept, or can we just configure the regular `mongod` service as a shard server?

**Comment by josephholsten** [comment]
Ultimately I'd like us to have a resource for a generic mongo service, with subclasses for each type.

I'd also like us to break out the cookbooks into a slightly more sane arrangement: https://github.com/edelight/chef-mongodb/issues/179

**Comment by nonflet** [comment]
Cann't wait longer ))) This need to be fixed :D

https://github.com/edelight/chef-mongodb/pull/201

**Comment by josephholsten** [comment]
@krukgit can you confirm that #201 &/ #205 fix this for you?

**Comment by josephholsten** [comment]
@krukgit @nonflet these patches should be in master now. Can you confirm they resolve your issue?

**Comment by nonflet** [comment]
Ok for me :)

**Comment by josephholsten** [comment]
@jamesonjlee looks like this can be closed
