### ISSUE TITLE
Changes to Replica Sets with key_file enabled must be executed against the PRIMARY

### ISSUE THREAD

**Issue by aaronbbrown** [edelight/chef-mongodb#176]
3 member replica set on Ubuntu 12.04 using MongoDB 2.4.8 with the following role applied:

```
{
  "name": "mongodb",
  "description": "MongoDB",
  "json_class": "Chef::Role",
  "default_attributes": {
  },
  "override_attributes": {
    "mongodb" : {
      "cluster_name" : "cube",
      "replicaset_name": "rs_cube",
      "install_method" : "10gen",
      "type": "mongod",
      "config": {
        "keyFile" : "/etc/mongodb.key",
        "replSet" : "rs_cube"
      },
      "key_file" : "/etc/mongodb.key",
      "key_file_content" : "abc123"
    }

  },
  "chef_type": "role",
  "run_list": [
    "recipe[mongodb::10gen_repo]",
    "recipe[mongodb::default]",
    "recipe[mongodb::replicaset]"
  ],
  "env_run_lists": {
  }
}
```

Chef is run sequentially mongo1, mongo2, mongo3.  mongo1, as expected does not build a replicasetas the search result is empty.  mongo2 successfully creates a 2 member replicaset with mongo2 as the PRIMARY.  When mongo3 attempts to converge, it cannot be added to the replica set and fails with the following error:

```
[2013-11-22T12:24:14+00:00] INFO: Configuring replicaset with members mongo1, mongo2, mongo3

================================================================================
Error executing action `create` on resource 'ruby_block[config_replicaset]'
================================================================================


Mongo::OperationFailure
-----------------------
not authorized for query on local.system.replset


Cookbook Trace:
---------------
/var/chef/cache/cookbooks/mongodb/libraries/mongodb.rb:112:in `configure_replicaset'
/var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:176:in `block (3 levels) in from_file'


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb

173:     ruby_block "config_replicaset" do
174:       block do
175:         if not replicaset.nil?
176:           MongoDB.configure_replicaset(replicaset, replicaset_name, rs_nodes)
177:         end
178:       end
179:       action :nothing



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:173:in `block in from_file'

ruby_block("config_replicaset") do
  params {:mongodb_type=>"mongod", :action=>[:enable, :start], :bind_ip=>nil, :port=>27017, :logpath=>"/var/log/mongodb", :dbpath=>"/var/lib/mongodb", :configserver=>[], :replicaset=>node[mongo3], :enable_rest=>false, :smallfiles=>false, :notifies=>[], :name=>"mongodb"}
  action [:nothing]
  retries 0
  retry_delay 2
  block_name "config_replicaset"
  cookbook_name "mongodb"
  recipe_name "replicaset"
  block #<Proc:0x0000000706fbb0@/var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:174>
end



[2013-11-22T12:24:15+00:00] ERROR: Running exception handlers
[2013-11-22T12:24:15+00:00] ERROR: Exception handlers complete
[2013-11-22T12:24:15+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-11-22T12:24:15+00:00] ERROR: ruby_block[config_replicaset] (mongodb::replicaset line 173) had an error: Mongo::OperationFailure: not authorized for query on local.system.replset
[2013-11-22T12:24:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

There are a few issues involved here:
1. Turning on keyFile also turns on auth, but no admin user is added by the cookbook
2. Only the PRIMARY node can add the node to the replica set: http://docs.mongodb.org/manual/tutorial/expand-replica-set/
   
   > Connect to the replica set’s primary.
   > You can only add members while connected to the primary. If you do not know which member is the primary, log into > any member of the replica set and issue the db.isMaster() command.
3. A 2 member replica set is somewhat nonsensical.  It might be worth only building replica sets once the number of nodes is odd, which would work around this problem in the case of a 3-member replica set (but not 5+).
4. Failing @ FATAL due to this error prevents the node from successfully writing its attributes back to the chef server, so a run on the PRIMARY doesn't add the member either.  Catching this error might actually solve the problem and allow a subsequent run on the PRIMARY to add the other nodes.

If there is no key_file specified, everything works as expected.

**Comment by gauravspatel** [comment]
Noticing problem on CentOS as well.  I get no permission allowed even when running chef-client on the primary node with key_file set:

[2013-12-02T23:49:03-05:00] WARN: Could not connect to database: 'localhost:27017', reason: Database command 'listDatabases' failed: (ok: '0.0'; errmsg: 'unauthorized').

**Comment by jamesonjlee** [comment]
yeah, the key_file variable needs to be tweaked a bit.

**Comment by josephholsten** [comment]
looks like I'll need to take this into consideration for #221

**Comment by zengwu** [comment]
ran into the same issues with mongodb 3.0.4, just wondering the problems are fixed?
