### ISSUE TITLE
0.14.x releases not present on opscode community site

### ISSUE THREAD

**Issue by benlangfeld** [edelight/chef-mongodb#177]
Could these please be uploaded?

**Comment by josephholsten** [comment]
@jamesonjlee did you ever get publishing access to the community site?

**Comment by jamesonjlee** [comment]
I have been hesitant to do this because 0.14 as-is will wreak havoc in replicaset/shard setups

**Comment by jeremyolliver** [comment]
So it's quite backwards incompatible? In my experience, many chef cookbooks frequently have backwards compatibility issues, and it's only the presence of a thorough `CHANGELOG.md` that points out those issues, and has a summary of the changes between versions that helps. Many official opscode cookbooks are pretty good at this.

I'd recommend that if you're going to move forward with anything on the community site, that it's inevitable, but a good changelog, and perhaps a link to it from the readme file, is the best you can do.

**Comment by josephholsten** [comment]
@jeremyolliver we're also working hard on getting all the backwards-incompatible changes usable so we can release a 1.0. You can see the current status of this stuff in our [Roadmap](https://github.com/edelight/chef-mongodb/issues/41#issuecomment-32674362)

**Comment by jeremyolliver** [comment]
Yep, I watch this repo for all notifications, and I've been following the roadmap getting on it's way, nice to see things shaping up :)

**Comment by et304383** [comment]
Would love to see the community updated please.  The community cookbook is non-functional on RHEL/Amazon which should be priority one.  RHEL is the most popular platform family for server installations and thus should work in any released version.

**Comment by jamesonjlee** [comment]
0.15.1 and 0.15.2 are now uploaded.  starting the 0.16.0 branch
