### ISSUE TITLE
[breaking change] Stop creating a mongodb_instance in mongodb::default

### ISSUE THREAD

**Issue by josephholsten** [edelight/chef-mongodb#179]
the logic of https://github.com/edelight/chef-mongodb/blob/master/recipes/default.rb#L42 is absolutely maddening in it's odd dependence on knowing exactly what recipes are in the run list. In particular, it doesn't play nice with wrapper cookbooks which may set up replicasets via `include_recipe`, not through node or role run lists. Don't get me started on mongos's search.

I propose:
- renaming helper recipes to begin with an underscore, including: `install` -> `_install_package`, `10gen_repo` -> `_mongodb_repo`,  
- keep 'standard' usage recipes top level:  `configserver`, `mongos`, `replicaset`, `shard`, and move the default instance into its own `mongod` recipe
- also move `mongo_gem` -> `ruby` to match opscode's mysql, xml, &c cookbooks
- have `default` not do anything!

**Comment by jamesonjlee** [comment]
well, ideally default would install from wherever but otherwise do nothing else.

**Comment by josephholsten** [comment]
Sounds reasonable, most cookbooks install a minimal client from their default, and the standard package is the only way to get the normal mongo client. 

## 

http://josephholsten.com

**Comment by josephholsten** [comment]
Moved to https://github.com/chef-brigade/mongodb-cookbook/issues/75
