### ISSUE TITLE
Redhat + actual MongoDB (2.4.8) + chef-mongodb 0.14.X don't work 

### ISSUE THREAD

**Issue by calmon** [edelight/chef-mongodb#181]
I ended up to specify the MongoDB package to '2.2.6-mongodb_1' and the newest chef-mongodb 0.13 release which finally did the job.

The error messages were various, I started to put in stuff manually just to get the next error. (Redhat 6.4)

**Comment by josephholsten** [comment]
@calmon could we see your configuration and logs? We test on CentOS 6.4, so this is a bit surprising.

**Comment by josephholsten** [comment]
@jameson it looks like we don't have enough to debug this and should close

@calmon if you're still having this problem and can get us more info, I'll be happy to help
