### ISSUE TITLE
Mms-agent "enabling" 

### ISSUE THREAD

**Issue by nonflet** [edelight/chef-mongodb#189]
Recipe: mongodb::mms-agent
- service[mms-agent] action enable
  Error executing action `enable` on resource 'service[mms-agent]'

Chef::Exceptions::UnsupportedAction
# Chef::Provider::Service::Init:0x000000021fc550 does not support :enable

Resource Declaration:
# In /var/chef/cache/cookbooks/runit/definitions/runit_service.rb

147:   service params[:name] do
148:     control_cmd = node[:runit][:sv_bin]
149:     if params[:owner]
150:       control_cmd = "#{node[:runit][:chpst_bin]} -u #{params[:owner]} #{control_cmd}"
151:     end
152:     provider Chef::Provider::Service::Init

Compiled Resource:
# Declared in /var/chef/cache/cookbooks/runit/definitions/runit_service.rb:147:in `block in from_file'

service("mms-agent") do
  params {:directory=>"/etc/sv", :only_if=>false, :finish_script=>false, :control=>[], :run_restart=>true, :active_directory=>"/etc/service", :owner=>"root", :group=>"root", :template_name=>"mms-agent", :log_template_name=>"mms-agent", :control_template_names=>{}, :finish_script_template_name=>"mms-agent", :start_command=>"start", :stop_command=>"stop", :restart_command=>"restart", :status_command=>"status", :options=>{:mms_agent_install_dir=>"/usr/local/share/mms-agent", :mms_agent_log_dir=>"/var/log/mongodb/mongodb.log/agent"}, :env=>{}, :cookbook=>"mongodb", :action=>:nothing, :name=>"mms-agent"}
  provider Chef::Provider::Service::Init
  action [:nothing]
  supports {:restart=>true, :status=>true}
  retries 0
  retry_delay 2
  service_name "mms-agent"
  pattern "mms-agent"
  start_command "/usr/bin/chpst -u root /usr/bin/sv start /etc/service/mms-agent"
  stop_command "/usr/bin/chpst -u root /usr/bin/sv stop /etc/service/mms-agent"
  status_command "/usr/bin/chpst -u root /usr/bin/sv status /etc/service/mms-agent"
  restart_command "/usr/bin/chpst -u root /usr/bin/sv restart /etc/service/mms-agent"
  startup_type :automatic
  cookbook_name "mongodb"
  recipe_name "mms-agent"
end

**Comment by josephholsten** [comment]
wow that's ugly. Also, you seem to be using an older version of the runit cookbook which has `runit_service` implemented as a definition instead of a resource. That's definitely not going to work with us attempting to notify the `runit_service`.

I guess we need to specify that we `depends 'runit', '>= 1.0'` in the `metadata.rb`

**Comment by josephholsten** [comment]
Are you using a version of the mongodb cookbook '<= 0.13.4'? More recent releases explicitly say we require runit `>=1.1.6`.

**Comment by nonflet** [comment]
Mmm, i will try one more time. I used fresh cookbook and dependencies , sure .

**Comment by josephholsten** [comment]
@nonflet is it still broken for you?

**Comment by nonflet** [comment]
Can check tomorrow. Can u wait ?

**Comment by josephholsten** [comment]
Of course!

**Comment by cggaurav** [comment]
+1

Commenting notifies :enable, mms_agent_service, :delayed works. 

This is definitely to with runit dependencies.

**Comment by josephholsten** [comment]
@jamesonjlee since we now specify a version in the runit dependency, this seems safe to close
