### ISSUE TITLE
actually use configserver values in mongos

### ISSUE THREAD

**Issue by josephholsten** [edelight/chef-mongodb#196]
so far as I can tell, the configserver nodes in mogodb_instance are entirely unused. This seems to be in error.

**Comment by josephholsten** [comment]
ah, it appears that what's going into `configserver` should be used to populate the `mongodb.config.configdb` attribute

**Comment by jamesonjlee** [comment]
yes, probably been getting around it because of explicitly setting configdb....

**Comment by josephholsten** [comment]
Moved to https://github.com/chef-brigade/mongodb-cookbook/issues/76
