### ISSUE TITLE
Improve code style consistency

### ISSUE THREAD

**Issue by jspiewak** [edelight/chef-mongodb#217]
Any thoughts on a pass through the code to try to make the [style](https://github.com/bbatsov/ruby-style-guide) a bit more consistent? 
- `'mongodb'` instead of `"mongodb"` when there is no interpolation
- `node[:mongodb][:config][:dbpath]` instead of `node['mongodb']['config']['dbpath']` (or vice versa, but consistent)
- `unless` instead of `if not`

Anything else?

**Comment by jamesonjlee** [comment]
yes, definitely.

I'm for `'string'` if it's a static string/selector, while `"string"` if it's a string regardless of interpolation
My preference is `node['mongodb']['config']['dbpath']` because it allows non-standard keys
`unless` is better yes.

honestly, we just need to turn on rubocup and foodcritic and fix all of those in a single swipe

**Comment by josephholsten** [comment]
bless you. +1 to rubocop and ruby-style-guide.

**Comment by josephholsten** [comment]
I personally don't like some of rubocop's defaults, but I'd rather use common style than have to think about it.

**Comment by jspiewak** [comment]
@jamesonjlee can you give me an example of a non-standard key (I am not actually fluent in Ruby, I am just good at mimicking what I see elsewhere. :stuck_out_tongue_closed_eyes: )? are they present in the cookbook?

not sure that I have a reason other than I think `node[:mongodb]` looks better than `node['mongodb']`. Is it possible to prefer that, and then have exceptions for when a non-standard key needs to be used?

Anyway, I care far more about consistency that which style.

Thank you @josephholsten for scratching the itch!

**Comment by jamesonjlee** [comment]
non-standard as in invalid,  I believe starting with numbers, having dashes/spaces are examples.

**Comment by josephholsten** [comment]
@jamesonjlee @jspiewak can we resolve this due to #220?
