### ISSUE TITLE
Config server recipe should run with --configsvr

### ISSUE THREAD

**Issue by stennie** [edelight/chef-mongodb#218]
A comment in the [configserver.rb recipe](https://github.com/edelight/chef-mongodb/blob/master/recipes/configserver.rb#L26-L28) suggests that --configsvr is not needed:

```
 we are not starting the configserver service with the --configsvr
 commandline option because right now this only changes the port it's
 running on, and we are overwriting this port anyway.
```

.. however it isn't entirely correct that --configsvr is only used to change the port.

There are some other internal defaults and sanity checks based on --configsvr, for example:

  # Don't allow a mongod to run as both --shardsvr and --configsvr
  https://github.com/mongodb/mongo/blob/v2.4/src/mongo/db/db.cpp#L1099

  # Set defaults for --configsvr
  https://github.com/mongodb/mongo/blob/v2.4/src/mongo/db/db.cpp#L1113

In particular, it looks like the Chef recipe is missing a default oplogSize (in 2.4 config servers have oplogs):
 http://docs.mongodb.org/manual/reference/configuration-options/#configsvr

The recipe should be updated to use --configsvr instead of assuming it is just a port default.  While that may have been true at some historical point, it isn't a safe assumption for future compatibility.

**Comment by josephholsten** [comment]
sounds sane.

**Comment by samperman** [comment]
You don't need to start it with the flag. Adding something like this to `defintions/mongodb.rb` will set the `configsvr` flag in `mongodb.conf`:

```
 if new_resource.type == "configserver"
  node[:mongodb][:config][:configsvr] = true
end
```

Just put that right above the templated created of the config file.

**Comment by jspiewak** [comment]
@stennie can you try #226 and see if that does what you need?

**Comment by stennie** [comment]
@jspiewak: Thanks for addressing. What version of the cookbook will this be included in?

**Comment by jspiewak** [comment]
Looks like 0.14.7 is the first version that has it.

**Comment by josephholsten** [comment]
Sounds like @stennie is satisfied. Ready to close?

**Comment by josephholsten** [comment]
@jamesonjlee seems safe to close
