### ISSUE TITLE
missing bson_ext gem causes chef run to fail

### ISSUE THREAD

**Issue by ctgswallow** [edelight/chef-mongodb#22]
``` diff
diff --git a/site-cookbooks/mongodb/recipes/default.rb b/site-cookbooks/mongodb/recipes/default.rb
index d107edb..c979a2f 100644
--- a/site-cookbooks/mongodb/recipes/default.rb
+++ b/site-cookbooks/mongodb/recipes/default.rb
@@ -23,6 +23,12 @@ package "mongodb" do
   action :install
 end

+# This missing gem stops chef.
+gem_package 'bson_ext' do
+  action :nothing
+end.run_action(:install)
+Gem.clear_paths
+
 needs_mongo_gem = (node.recipes.include?("mongodb::replicaset") or node.recipes.include?("mongodb::mongos"))

 if needs_mongo_gem
```

**Comment by miketheman** [comment]
Considering that:
1. The bson_ext gem is the C extensions to accelerate mongodb actions via the ruby driver
2. The only interaction via the ruby driver here is administrative
3. The chef-run doesn't fail, just spits out some info messages about bson_ext

I am leaning towards closing this issue. Requiring the installation of another gem that has lower-level dependencies and compilation time may not be optimal.
