### ISSUE TITLE
Signed vs. Unsigned RPMs

### ISSUE THREAD

**Issue by codebudo** [edelight/chef-mongodb#223]
It seems unclear weather the official RPMs from 10gen/mongodb should be signed or unsigned. This commit seems to think that they should be signed https://github.com/edelight/chef-mongodb/commit/89bd82d0129be663900af3272316a6e969ce15f1#diff-c2da2cae25350f23bffb37a1a7d6baf4L44

but the docs on the website say `gpgcheck=0` for the repo. http://docs.mongodb.org/manual/tutorial/install-mongodb-on-red-hat-centos-or-fedora-linux/

When trying to actually install the RPMs it does appear that they are unsigned and the /etc/yum.repos.d/10gen.repo file should specify `gpgcheck=0`. I'm not particularly picky about the gpgcheck, but it would be nice for the mongodb::10gen_repo recipe to specify `gpgcheck false` until the RPMs are signed.

For reference, this is how I discovered the gpgcheck was causing the problem:
http://stackoverflow.com/questions/20782380/unable-to-install-mongodb-with-chef-server

**Comment by jamesonjlee** [comment]
I believe I had to remove that option because it required that we pin the yum cookbook to be `> 3.0.0` which is not backwards compatible with Chef 10.

We will drop support for Chef10 at some point where we can have the `gpgcheck false` back, but it should work right now since we explicitly set the packager opt to disable gpg check here:
https://github.com/edelight/chef-mongodb/blob/master/recipes/install.rb#L70

are you not able to install using the current version of the cookbook?

**Comment by codebudo** [comment]
Yea, the current version of the cookbook produces exactly the same error as I saw in the stackoverflow thread. Here's my vital stats:

``` BASH
$ uname -a
Linux localhost.localdomain 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ vagrant --version
Vagrant 1.4.3
$ chef-solo --version
Chef: 11.8.2
```

Adding `gpgcheck false` to the recipe fixed the problem immediately. I'm assuming the RPMs being served from http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/ are simply not signed or incorrectly signed.

I made a fork with the one line change so librarian-chef could pick it up. I could submit a pull request if you like.

**Comment by jamesonjlee** [comment]
what version of the yum cookbook are you using? and yeah mongodb's package are not signed.

**Comment by codebudo** [comment]
The yum cookbook I'm using is version '3.0.6'.

I think I see what's up now. I'm using librarian-chef and requesting the mongodb cookbook like this in the Cheffile.
`cookbook 'mongodb'`
This gives me version "0.13.7".
When I specify this repo
`cookbook 'mongodb', :git => 'git@github.com:edelight/chef-mongodb.git'`
I get version "0.14.6", which works just fine. Cool.

Alright, sorry for the disturbance. I guess librarian-chef is pulling the cookbook from somewhere else. Strange, but not an issue for this repo. Closing.

Thank you for your help!

**Comment by jamesonjlee** [comment]
that's the latest on the community site I believe, I have not uploaded 0.14.X branch to the community site for certain reasons.
