### ISSUE TITLE
dbpath does not get removed from mongodb.conf for mongos nodes

### ISSUE THREAD

**Issue by dquiles** [edelight/chef-mongodb#235]
This does not delete dbpath attrib from mongodb.conf for mongos node...
https://github.com/edelight/chef-mongodb/blob/master/definitions/mongodb.rb#L112

It also throws a attribute precedence error...ie,
## Chef::Exceptions::ImmutableAttributeModification

Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
## Relevant File Content:

/var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:

112>>     node[:mongodb][:config].delete('dbpath')

This works correctly even though its a hacky fix...
https://github.com/edelight/chef-mongodb/pull/213/files#diff-1003631c496d9e5908573355cbd09867R14

**Comment by jspiewak** [comment]
Yep, we just ran into this yesterday as we were working on upgrading to Chef 11.8.2
We will have a PR some time today.

**Comment by jamesonjlee** [comment]
I think it should be set to 'nil' since the template generator explicitly ignores nils. how is this https://github.com/edelight/chef-mongodb/commit/4d363fd906e9747f04d8bcda7f702246aaa35c47

**Comment by jspiewak** [comment]
I comment in the commit, but I was thinking force_override, and we had a few other problems in this realm that I was going to capture. Testing them out now.

**Comment by jamesonjlee** [comment]
marking as fixed.

**Comment by dquiles** [comment]
Even when set to nil, dbpath still appends to config default value.

**Comment by jamesonjlee** [comment]
@dquiles that's because of the issue raised in #237 that the way new_resource is getting node attribute appears to be a copy and does not get updated.
