### ISSUE TITLE
configservers no longer populating since latest commit

### ISSUE THREAD

**Issue by dquiles** [edelight/chef-mongodb#239]
# 
# Error executing action `start` on resource 'service[mongos]'
## Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service mongos start ----
STDOUT: Starting mongos: warning: remove or comment out this line by starting it with '#', skipping now : nojournal = false
warning: remove or comment out this line by starting it with '#', skipping now : rest = false
warning: remove or comment out this line by starting it with '#', skipping now : smallfiles = false
warning: bind_ip of 0.0.0.0 is unnecessary; listens on all ips by default
Sat Feb  8 21:14:01.961 need either 1 or 3 configdbs
[FAILED]
STDERR:
---- End output of /sbin/service mongos start ----
Ran /sbin/service mongos start returned 1
## Resource Declaration:
# In /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb

187:   service new_resource.name do
188:     provider Chef::Provider::Service::Upstart if node['mongodb']['apt_repo'] == 'ubuntu-upstart'
189:     supports :status => true, :restart => true
190:     action new_resource.service_action
191:     new_resource.service_notifies.each do |service_notify|
192:       notifies :run, service_notify
193:     end
194:     notifies :create, 'ruby_block[config_replicaset]' if new_resource.is_replicaset && new_resource.auto_configure_replicaset
195:     notifies :create, 'ruby_block[config_sharding]', :immediately if new_resource.type == 'mongos' && new_resource.auto_configure_sharding
196:       # we don't care about a running mongodb service in these cases, all we need is stopping it
197:     ignore_failure true if new_resource.name == 'mongodb'
198:   end
199:
200:   # replicaset
201:   if new_resource.is_replicaset && new_resource.auto_configure_replicaset
202:     rs_nodes = search(
203:       :node,
204:       "mongodb_cluster_name:#{new_resource.replicaset['mongodb']['cluster_name']} AND \
205:        mongodb_is_replicaset:true AND \
206:        mongodb_shard_name:#{new_resource.replicaset['mongodb']['shard_name']} AND \
207:        chef_environment:#{new_resource.replicaset.chef_environment}"
208:     )
209:
210:     ruby_block 'config_replicaset' do
211:       block do
212:         MongoDB.configure_replicaset(new_resource.replicaset, replicaset_name, rs_nodes) unless new_resource.replicaset.nil?
213:       end
214:       action :nothing
215:     end
216:
217:     ruby_block 'run_config_replicaset' do
218:       block {}
219:       notifies :create, 'ruby_block[config_replicaset]'
220:     end
221:   end
222:
## Compiled Resource:
# Declared in /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:187:in `block in from_file'

service("mongos") do
  params {:mongodb_type=>"mongos", :action=>[:enable, :start], :logpath=>"/data/log/stats/mongodb.log", :dbpath=>"/var/lib/mongodb", :configservers=>[], :replicaset=>nil, :notifies=>[], :port=>27017, :configsrvs=>[], :enable_rest=>false, :smallfiles=>false, :name=>"mongos"}
  action [:enable, :start]
  supports {:status=>true, :restart=>true}
  retries 0
  retry_delay 2
  service_name "mongos"
  enabled true
  pattern "mongos"
  startup_type :automatic
  cookbook_name "mongodb"
  recipe_name "mongos"
end

[2014-02-08T21:14:01-05:00] ERROR: Running exception handlers
[2014-02-08T21:14:01-05:00] ERROR: Exception handlers complete
[2014-02-08T21:14:01-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 17 resources updated
[2014-02-08T21:14:02-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by dquiles** [comment]
Var is incorrect

https://github.com/edelight/chef-mongodb/blob/master/recipes/mongos.rb#L26

https://github.com/edelight/chef-mongodb/blob/master/recipes/mongos.rb#L46

**Comment by jamesonjlee** [comment]
fixed on 7168080ff45523c79c96eed5498843738468df6e thank you for catching, we need to write a test for that.
