### ISSUE TITLE
mongos question

### ISSUE THREAD

**Issue by dquiles** [edelight/chef-mongodb#245]
is it possible to have multiple mongos configs on a single node?

**Comment by jamesonjlee** [comment]
currently no, in theory yes!

**Comment by dquiles** [comment]
Yeah I do it now manually, wanted to use the cookbook to do it...

**Comment by jamesonjlee** [comment]
yeah, it isn't a focus because it's a setup that's not recommend.  If you are talking about testing setups I have a branch I am testing with https://github.com/chrisroberts/vagabond that does multi-node environment with LXC on a single host.

**Comment by josephholsten** [comment]
Seems like a duplicate of #270.

@jamesonjlee seems like we can close this.
