### ISSUE TITLE
Ports for co-existing shard and config server

### ISSUE THREAD

**Issue by othatbrian** [edelight/chef-mongodb#25]
It appears to me that this cookbook won't handle the case of trying to run a shard and config server on the same host (because they require different ports). Does that seem correct, or am I not doing something right?

**Comment by thekorn** [comment]
Hey @bdstevens,
yes you are right, this cookbook only supports a single mongodb instance per machine.

Markus

**Comment by sdarwin** [comment]
Isn't this actually a major problem then?

There are 3 instances supported: mongos, shard server, and config server.     And each of them must be on a totally different machine, using this cookbook?

**Comment by jamesonjlee** [comment]
this is an issue that would be solved by using LWRPs (such that the cookbook no longer is required to set most of the custom variables).

**Comment by sdarwin** [comment]
Using LWRPs sounds like overkill, perhaps, for this particular issue.   Or... I am not picturing what you mean exactly.

But anyway, nevermind.  I fixed it.  :-)))

**Comment by josephholsten** [comment]
Supporting multiple mongodb processes on the same box is a current goal, see esp #194. This work will be somewhat backwards incompatible though, so it won't be included until the next major revision.

**Comment by josephholsten** [comment]
@jamesonjlee can we close this in favor of #278?
