### ISSUE TITLE
Update mms agent recipe for new packaging

### ISSUE THREAD

**Issue by jspiewak** [edelight/chef-mongodb#260]
MongoDB now provides .deb and .rpm packages. They also provide a backup agent.

I am working on revamping the existing mms_agent recipe and adding an mms_backup_agent recipe to make use of these. Just wanted to add the issue so others would know it is in flight.

**Comment by jamesonjlee** [comment]
oh sweet jesus thank you.

**Comment by jspiewak** [comment]
#261 fulfills this issue.
