### ISSUE TITLE
Get Travis-CI or equivalent fully set up

### ISSUE THREAD

**Issue by jspiewak** [edelight/chef-mongodb#265]
So it builds pull requests and runs the kitchen tests.
I was able to set it up against my fork, but I suspect that an owner of the repo needs to do it for real.

**Comment by jamesonjlee** [comment]
yeah, the repo owner is @edelight @thekorn (@tobami ?) has that access.

**Comment by jspiewak** [comment]
Given that you have commit privs, do you want to sign into travis ci and see if the repo shows up for you, @jamesonjlee ?

**Comment by jamesonjlee** [comment]
I only have collab access, but not admin access (so no access to hooks)

**Comment by tobami** [comment]
Closed by 2c6486f

**Comment by tobami** [comment]
I also added the travis badge :smile:

**Comment by jspiewak** [comment]
Thank you!
