### ISSUE TITLE
config_replicaset fails to create replicaset

### ISSUE THREAD

**Issue by sclausson** [edelight/chef-mongodb#283]
[2014-04-08T07:02:32-04:00] INFO: Processing ruby_block[config_replicaset] action create (mongodb::replicaset line 211)
[2014-04-08T07:02:33-04:00] INFO: Configuring replicaset with members ip-10-1-13-192, ip-10-1-20-99, ip-10-1-4-70
<B>[2014-04-08T07:02:33-04:00] ERROR: Failed to configure replicaset, reason: {"ok"=>0.0, "errmsg"=>"couldn't parse cfg object bad config for member[0] unexpected or missing type value in BSON object"}</B>

**Comment by jspiewak** [comment]
Could you give us some more information about your setup?
What version of the cookbook? What version of mongo? What OS? Which member had this problem? Did the other nodes work? If another node worked, what does rs.config() say?

**Comment by sclausson** [comment]
Cookbook version: 0.16.0
Mongo version: 2.4.10
Platform: RHEL 6.4

This is a new 3 node cluster/replicaSet.  I am passing in variables / run list in a json file, and running on each node (I get the same error regardless of the node I perform the chef run on).
{
    "mongodb": {
        "cluster_name": "SMCM-999-87",
        "is_replicaset": "true",
        "config": {
            "logpath": "/log/mongodb",
            "dbpath": "/data/mongodb",
            "replSet": "rs0",
            "nohttpinterface": "true"
        },
        "package_version": "2.4.10-mongodb_1",
        "replica_priority": "5"
    },
    "run_list": [
        "recipe[mongodb::10gen_repo]",
        "recipe[mongodb::replicaset]"
    ]
}

**Comment by jspiewak** [comment]
Well, I added centos-6.4 to the kitchen yml and fired off the replicaset converge for it and it worked. So much for figuring this out quickly...

**Comment by sclausson** [comment]
I'll do some more testing and see if I can figure anything out that might be odd about my configuration.  Thanks for having a look!

**Comment by sclausson** [comment]
For what it's worth this is what the mongo log states:
Wed Apr  9 07:46:09.153 [conn5] replSet replSetInitiate admin command received from client
Wed Apr  9 07:46:09.153 [conn5] Assertion: 13118:unexpected or missing type value in BSON object

The command that is sent to mongo shell:

<b>command admin.$cmd command: { replSetInitiate: { _id: "rs0", members: [ { _id: 0, host: "SMCMDB01.ctp.dev.com:27017", priority: "10" }, { _id: 1, host: "SMCMDB02.ctp.dev.com:27017", priority: "5" }, { _id: 2, host: "SMCMDB03.ctp.dev.com:27017", priority: "2" } ] } }</b> ntoreturn:1 keyUpdates:0 locks(micros) W:703 reslen:148 224ms

**Comment by jspiewak** [comment]
So at a guess it is that the priority is being set as a string.
http://docs.mongodb.org/manual/reference/replica-configuration/#replica-set-reconfiguration-usage

Try leaving off the priority for now and see if you make progress.

**Comment by jspiewak** [comment]
Or unquote it.

**Comment by sclausson** [comment]
Bingo!  I've changed the attribute to "replica_priority" : 5 instead of "5" and all is working great now.  Thanks for the help!

**Comment by jspiewak** [comment]
No problem.
