### ISSUE TITLE
Fresh mongodb

### ISSUE THREAD

**Issue by matyunin** [edelight/chef-mongodb#284]
Hello! Why you dont use fresh package `mongodb-org` (2.6.1) from 10gen repo? In cookbook we have outdated `2.4.10` version.

http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/

> Ubuntu 12.04.4 LTS x64

**Comment by jspiewak** [comment]
If you set `node.override[:mongodb][:package_name] = mongodb-org` does it work for you?

**Comment by matyunin** [comment]
It works, thanks @jspiewak !

`role.json`:

``` json
.............
"mongodb": {
    "package_version": "2.6.0",
    "package_name": "mongodb-org"
}
.............
```
