### ISSUE TITLE
Bump cookbook version on opscode site

### ISSUE THREAD

**Issue by holms** [edelight/chef-mongodb#286]
As you can see here ( https://github.com/edelight/chef-mongodb/commit/8c49220b46788e4d85e92b3b905a914b3ea693dd ), yum cookbook locked at "< 3" which brings a problem for "yum-epel" cookbook, which I'm using in my project. 

And Berkshelf picks older chef-mongodb version. You can check situation in here: https://github.com/berkshelf/berkshelf/issues/1149

On 0.16.0 this is solved. Please update version on opscode site :+1:

**Comment by holms** [comment]
and actually with old version I've got this problem when installing mongo

`package mongodb-org-server-2.6.1-0.1.rc0.x86_64.rpm is not signed`

**Comment by jamesonjlee** [comment]
0.16.0 is now live on the community site, thanks for reminding me.
