### ISSUE TITLE
No Syslog Support

### ISSUE THREAD

**Issue by grampajoe** [edelight/chef-mongodb#288]
When using the `syslog` option, the `logpath` option [can't be used](http://docs.mongodb.org/v2.4/reference/configuration-options/#syslog).

Currently, it's not possible to remove `logpath` from the config file without overriding the template, which requires making a copy of all `mongodb`'s templates in a new cookbook.

It should be possible to set `node[:mongodb][:config][:logpath]` to `nil` or to delete the attribute so it isn't included in the config file. An alternative could be to check for the `node[:mongodb][:config][:syslog]` attribute and suppress output of the `logpath` setting.

**Comment by jamesonjlee** [comment]
logpath should not be in the configuration if you set `node['mongodb']['config']['logpath'] = nil` ?
https://github.com/edelight/chef-mongodb/blob/master/templates/default/mongodb.conf.erb#L6

**Comment by grampajoe** [comment]
That's true, it won't be in the template, but then this will fail: https://github.com/edelight/chef-mongodb/blob/master/definitions/mongodb.rb#L152-L158

**Comment by jamesonjlee** [comment]
ah, yes we should fix that.

**Comment by ranman** [comment]
this can be closed?

**Comment by jamesonjlee** [comment]
@grampajoe did my patch fix the issue?

**Comment by grampajoe** [comment]
@jamesonjlee I'll see if I can get to testing it today. Thanks!

**Comment by grampajoe** [comment]
@jamesonjlee Yes! This seems to have been fixed.
