### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by hannesvdvreken** [edelight/chef-mongodb#299]
Earlier if you installed from the 10gen package repository it installed mongodb-10gen by default. 

New versions from MongoDB can no longer be installed by doing `apt-get install mongodb-10gen`. You need to do `apt-get install mongodb-org`, which has been changed by the [latest commits](https://github.com/edelight/chef-mongodb/compare/0.16.0...master).

Sources:
https://github.com/edelight/chef-mongodb/blob/0.16.0/recipes/10gen_repo.rb#L36
https://github.com/edelight/chef-mongodb/blob/master/recipes/mongodb_org_repo.rb#L24
http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/10gen/binary-amd64/

In order to get the latest and greatest from this cookbook, one has to download via git instead of letting librarian-chef/berkshelf get the best version via community api site.

**Comment by jamesonjlee** [comment]
done.
