### ISSUE TITLE
Break Backward Compatibility

### ISSUE THREAD

**Issue by josephholsten** [edelight/chef-mongodb#308]
Someday soon we're going to have to break backwards compatibility, and we may as well rip the bandage off. This is a tracking ticket for all the backwards incompatible changes that should go into the next breaking release (1.0?).
- #6 allow arbitrary shard names
- #95 separate shard and replicaset names
- #153 remove references to 10gen
- #158 support compound sharding keys
- #179 stop creating a `mongodb_instance` in `mongodb::default`
- #262 update default paths to match mongodb defaults
- #309 use yaml format config, incompatible with < 2.6 mongo

**Comment by thomas-riccardi** [comment]
From the CHANGELOG: `DEPRECATE '10gen_repo' for 'mongodb_org_repo' #287 (dropping in 0.16.2)`. Please don't do that until major version change, ie _not_ in 0.16.2.
(Also, the README still refers to 10gen_repo).

**Comment by josephholsten** [comment]
Moved to https://github.com/chef-brigade/mongodb-cookbook/issues/78
