### ISSUE TITLE
Support YAML config file

### ISSUE THREAD

**Issue by josephholsten** [edelight/chef-mongodb#309]
Per the mongo doc for [Configuration Options](http://docs.mongodb.org/manual/reference/configuration-options/):

> Changed in version 2.6: MongoDB introduces a YAML-based configuration file format. The 2.4 configuration file format remains for backward compatibility.

It also moves the options to totally different locations.

Obviously, this is a breaking change.

**Comment by jamesonjlee** [comment]
if we are doing the configuration correctly we should be able to just do .to_yaml on a hash obj.

**Comment by josephholsten** [comment]
It should be straightforward for the basic serialization, but the gross structure is entirely different. To demonstrate:

old-style boost::program_options format

``` ruby
{
  'port' => 27017,
  'bind_ip' => '0.0.0.0',
  'rest' => false,

  'fork' => false,

  'dbpath' => '/var/lib/mongodb',
  'nojournal' => false,
  'smallfiles' => false

  'logpath' => '/var/log/mongodb/mongodb.log',
  'logappend' => true,,

  'keyFile' => '/etc/mongodb.key'
}
```

new-style YAML format

``` ruby
{
  'net' => {
    'port' => 27017,
    'bindIp' => '0.0.0.0',
    'http' => {
      'RESTInterfaceEnabled' => false,
    },
  },
  'processManagement' => {
     'fork' => false,
  },
  'storage' => {
    'dbPath' => '/var/lib/mongodb',
    'smallFiles' => false,
    'journal' => {
      'enabled' => true,
    },
  },
  'systemLog' => {
    'destination' => 'file',
    'path' => '/var/log/mongodb/mongodb.log',
    'logAppend' => true,
  },
  'security' => {
    'keyFile' => '/etc/mongodb.key'
  }
}
```

**Comment by jamesonjlee** [comment]
node['mongodb']['configuration_style'] = 'boost' # or 'yaml'
then we treat the config output as yaml? oh god the special cases... maybe we can library that out?

**Comment by josephholsten** [comment]
yeah, I've been thinking about finding the maintainers of the puppet module for mongo, and buying them enough drinks until they agree to merge all their support code with ours.

**Comment by jamesonjlee** [comment]
I will be happy to add funds to that ;)

**Comment by hannesvdvreken** [comment]
I'll have some time next week. I'll take a look and see if I can start working on that to allow yaml config files.

**Comment by josephholsten** [comment]
@hannesvdvreken I'd start with porting our default values ignoring backward-compatibility. I'd like to get a sense of what the future looks like before we figure out a migration path.

**Comment by josephholsten** [comment]
moved to https://github.com/chef-brigade/mongodb-cookbook/issues/72
