### ISSUE TITLE
Co-maintainer?

### ISSUE THREAD

**Issue by patcon** [edelight/chef-mongodb#31]
Hi there,

I'm just coming across this cookbook and realizing that there are quite a number of pull requests left hanging. I'm not sure I'd be the right person to help, as I'm not a heavy mongoDB user, but I was wondering whether you would consider giving some of the other trusted contributors push access to the repo. Just thinking it might help keep things moving, and prevent people from forking and splitting efforts needlessly :)

Cheers!

PS - Would anyone else reading this be interested in helping to co-maintain?

**Comment by thekorn** [comment]
Hello Patrick,
thanks for stepping up and offering your help! Your help is very much appreciated!
We just gave you push rights to the repository, I will come back to you at the beginning of next week so we can coordinate work on this project.

Welcome on board, as a co-maintainer of the MongoDB cookbook for chef.

Markus

**Comment by tobami** [comment]
So, is there anyone else who wants push ritghts?

**Comment by patcon** [comment]
haha thanks markus! In all honesty, I only came across the need for this cookbook in setting up graylog2, so while I'm happy to participate in the queues to the best of my ability, there might be others who have more skin in the game :)

//cc @cwjohnston @jamesonjlee @ctgswallow @doxavore @nathenharvey @fooforge

**Comment by miketheman** [comment]
Hi there! Both myself and @dcrosta have both written a fair amount of chef/mongo integration as well, and would like to get to the point of "The One Cookbook".
We created another one over [here](https://github.com/miketheman/fullstack/tree/master/cookbooks/mongodb) for a specific project, not nearly as full-featured.

**Comment by tobami** [comment]
@miketheman I gave you both push rights

**Comment by tobami** [comment]
@patcon haha, do _all_ of them want to participate?

**Comment by tobami** [comment]
I just created a tentative [roadmap page](https://github.com/edelight/chef-cookbooks/wiki/Roadmap).

Feel free to edit it, so that we can all agree on the future direction.

**Comment by patcon** [comment]
@tobami haha no idea, but just calling this issue to their attention, and I'm sure they'll speak up if interested :)

And thanks for the roadmap man

**Comment by jamesonjlee** [comment]
I'm interested as we are actively working with mongodb (and submitting pull-reqs), but I would have to verify with HR about becoming a maintainer.

**Comment by tobami** [comment]
@jamesonjlee you have now push rights!

**Comment by jamesonjlee** [comment]
@thekorn @tobami I think we need some more maintainers, also I've also accidentally auto piloted myself out of the org, if you could re-add me that would be swell.

**Comment by tobami** [comment]
@jamesonjlee just added you. Yeah more maintainers would be good, the cookbook and issues got quite complex over the years.
