### ISSUE TITLE
runit dependency obsolete?

### ISSUE THREAD

**Issue by lxndrp** [edelight/chef-mongodb#354]
Folks,

we are currently cleaning up our dependencies and removing old cookbook versions from our chef server. Looking through the cookbooks, I noticed that `mongodb` has an `runit` dependency, but frankly, I couldn't find any reference to it in the cookbook.

Is that one obsolete, or am I missing something?

Cheers,
Alexander

**Comment by jamesonjlee** [comment]
I think it's an old dependency, removed it.

**Comment by jamesonjlee** [comment]
yeah, I believe it was a dependency on the old mms agents.
