### ISSUE TITLE
Increased nofile limit

### ISSUE THREAD

**Issue by josephholsten** [edelight/chef-mongodb#37]
The only way I know to bump mongodb's nofile limit is to add a line like `ulimit -n 65535` to the init script. This is unpleasant, but I don't know any other way at the moment.

Because the init script uses start-stop-daemon, it does not use a pam session (http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=406942). Because it does not use a pam session, it does not access limits from /etc/security/limits.conf. 

A traditional way of raising mongodb's nofile limit would be to have a /etc/security/limits.d/50-mongodb file containing

```
mongodb - nofile 65535
```

and ensure that /etc/pam.d/common-session (and /etc/pam.d/common-session-noninteractive if it exists) contain the line

```
session required        pam_limits.so
```

I see that updating the [deb-style init script](https://github.com/mongodb/mongo/blob/master/debian/init.d) won't remove s-s-d, so that's not a solution.

Does anyone have a better way of bumping mongodb's nofile limit?

**Comment by miketheman** [comment]
Currently, the ulimit specified in the [init file that comes in mongodb rpm packages](https://github.com/mongodb/mongo/blob/master/rpm/init.d-mongod#L69) does this.

Also, there's a hard-coded limit of 20000 in the source code.

**Comment by jamesonjlee** [comment]
closes with 3f35a1 and f6c94
