### ISSUE TITLE
making the repository RightScale-friendly?

### ISSUE THREAD

**Issue by TTimo** [edelight/chef-mongodb#38]
I am trying to spinup a MongoDB instance through RightScale (https://my.rightscale.com/library/server_templates/MongoDB/lineage/2094).

The template at RightScale tries to use this repository: git://github.com/edelight/chef-cookbooks.git, which has been replaced by this new one: https://github.com/edelight/chef-mongodb

So I am trying to update the configuration, but it seems some items are missing in the new repository, and the logic on RightScale side isn't seeing the recipes? This may very well be an issue on RightScale, I am posting this in case you know how to fix it.

If there is an archive of the old repository, could I get access to it from comparison?

**Comment by miketheman** [comment]
@TTimo,

The RightScale link is not open to the world, I cannot see that without a login to RightScale.

The repository went through a change to promote the cookbook to a first-class citizen and rename the repo accordingly.

You can find the last version of the repo in the prior state at this commit d77f3162a9f7ffddf280ec50352d979784d9bb02.

Hope this helps,
-M

**Comment by TTimo** [comment]
Thank you! Yes, that helped quite a bit actually. I would like to use the latest in the repository eventually, but that will require Chef knowledge that I don't have at this point. But I was able to fix things up to the old revision..

**Comment by tobami** [comment]
It sure doesn't help that the last version of the cookbook uploaded to the community site doesn't point to the new url. We'll upload the new version ASAP

**Comment by TTimo** [comment]
I was able to fix it up on my cloned template, but it still failed during boot saying it couldn't find the cookbook .. the repo path was fine though .. I'm just going to try and find a ready to go AMI outside of RightScale for now, this is just for experimentation purposes right now

**Comment by miketheman** [comment]
@tobami - if you can push to the community site, can you edit the metadata there as well?

**Comment by tobami** [comment]
Done. @thekorn updated the metadata as well. We should also have git tagged and chef versioned, but well, we'll do that after the next PR merge.

**Comment by TTimo** [comment]
Sorry, I'm a Chef noob .. where is that 'community site' and the package with metadata that you uploaded? That may help me get a working template going as well :)

**Comment by tobami** [comment]
The community site is where release versions of opscode and non-opscode cookbooks are uploaded. It has an API, and there are several tools that use it to "get" a given cookbooks. For this cookbook, there is a community site here: http://community.opscode.com/cookbooks/mongodb

**Comment by TTimo** [comment]
FYI, the RightScale folks have confirmed that the package uploaded to opscode is of little use for working with this cookbook within the RS infrastructure. I have forked the repo at https://github.com/TTimo/chef-mongodb and started making changes towards compatibility.
