### ISSUE TITLE
Can't start config server

### ISSUE THREAD

**Issue by blake41** [edelight/chef-mongodb#52]
I'm going to apologize in advance for this, but I'm struggling with a pretty simple mongo setup running.  If I run just the  "mongodb::default" recipe I have no problems.  But if I try and add the configserver or mongos recipes I run into problems.  It appears the problem is that my /var/run/confiserver.pid  has root permissions but that init.d script the recipe calls to start the configserver runs mongo as its own user and errors when it tries to write to the pid file.  I'ts not clear to me why the process that creates the pidfile (which i assume is the mongo user) doesnt create it with mongodb as the user as opposed to the root user.  I imagine I must be doing something idiotic because I can't find anyone with a similar problem so apologies if this is obvious to everyone but myself.  Any leads would be helpful.

The exact chef stacktrace is 
Chef::Exceptions::Exec: service[configserver](mongodb::configserver line 140) had an error: Chef::Exceptions::Exec: /usr/sbin/invoke-rc.d configserver start returned 1, expected 0

**Comment by josephholsten** [comment]
sorry for the huge delay! I'm adding a test for that now.

**Comment by josephholsten** [comment]
hmm, that's no good. looks like it's not properly shutting down mongodb before trying to start up the configserver process. #205 is supposed to redress this use case, but for the moment I've added #208 to test the problem.

**Comment by josephholsten** [comment]
#208 indicates this is resolved

**Comment by josephholsten** [comment]
@jamesonjlee this seems safe to close
