### ISSUE TITLE
Makefile only works if checkout directory is 'mongodb'

### ISSUE THREAD

**Issue by TTimo** [edelight/chef-mongodb#53]
I needed to generate the metadata.json file, and found out that the Makefile would not work unless the git tree is cloned into a folder named 'mongodb' .. by default git would clone to 'chef-mongodb' from github, which doesn't work.

More specifically, this is the problem command:

```
knife cookbook metadata -o .. mongodb
```

This works 'by luck' when the repository folder is named 'mongodb', and the recipes are in the 'mongodb' folder basically.

My knowledge of Chef tools is limited, I haven't found a way to fix this so I'm just renaming for now.

**Comment by miketheman** [comment]
We could probably add an entry o `metadata.rb` as `name: mongodb` to accomplish this.

**Comment by TTimo** [comment]
Just tried, doing that alone doesn't do the trick.

**Comment by jamesonjlee** [comment]
this is true, (and still is), the package name and the directory must match, but there isn't much we can do about that from inside the cookbook.

the ideal way would be for edelight to rename the repo (with all the fun issues that comes with it) or...
berkshelf/librarian/etc.

I suggest the latter, and will close the issue as such.
