### ISSUE TITLE
mongo is restarted every time chef-client runs

### ISSUE THREAD

**Issue by milosgajdos** [edelight/chef-mongodb#55]
Every time chef-client runs, mongo is restarted on each node. This is a bit annoying because when the mongos are restarted in the replicaset, the master moves to another node and becomes a slave and one of the slaves become master. Is there any way to avoid unnecessary restarts ?
I'm not able to figure out why are the restarts happening when it looks like they shouldnt.

**Comment by jamesonjlee** [comment]
see issue #36, it because the current release forces a restart because of change in init scripts.
