### ISSUE TITLE
replicaset recipe failing - No such file or directory - /etc/chef/client.pem

### ISSUE THREAD

**Issue by TTimo** [edelight/chef-mongodb#56]
mongodb::default is working fine, I have a setup that creates a standalone MongoDB just fine, but I can't seem to add a mongodb::replicaset without getting the error below about chef.pem

I was able to manually configure a replicaset though, and it didn't involve chef.pem anywhere.

Any suggestions?

```
18:29:34: *** Chef 0.10.10.2 ***
18:29:39: Setting the run_list to ["mongodb::replicaset"] from JSON
18:29:39: Run List is [recipe[mongodb::replicaset]]
18:29:39: Run List expands to [mongodb::replicaset]
18:29:39: Starting Chef Run for ip-10-118-107-131.ec2.internal
18:29:39: Processing gem_package[mongo] action install (mongodb::default line 30)
18:29:39: Processing gem_package[mongo] action install (mongodb::default line 30)
18:29:39: We are not using a configfile, as the daemons can be configured via commandline
18:29:39: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory - /etc/chef/client.pem>
*ERROR> Execution failed
*ERROR> Execution error:
I cannot read /etc/chef/client.pem, which you told me to use to sign requests!

The error occurred line 63 of /opt/rightscale/sandbox/lib/ruby/gems/1.8/gems/chef-0.10.10.2/lib/chef/rest/auth_credentials.rb in method 'load_signing_key' while executing:

61       rescue SystemCallError, IOError => e
62         Chef::Log.warn "Failed to read the private key #{key_file}: #{e.inspect}"
**         raise Chef::Exceptions::PrivateKeyMissing, "I cannot read #{key_file}, which you told me to use to sign requests!"
64       rescue OpenSSL::PKey::RSAError
65         msg = "The file #{key_file} does not contain a correctly formatted private key.\n"

*ERROR> Subprocess exited with 1
*RS> failed: mongodb::replicaset
'''
```

**Comment by liminal** [comment]
The use of search in definitions/mongodb.rb:158 pretty much makes it impossible to use this recipe with Chef-Solo since search is only available if you run against a server.

**Comment by TTimo** [comment]
That wasn't under Chef-Solo afaik.

Closing this. I don't need a resolution anymore, turns out Chef wasn't really needed or a great help even if it worked for configuring MongoDB.

**Comment by robmoore** [comment]
Could chef-solo-search somehow be combined with this so allow it to run with Chef solo?

**Comment by josephholsten** [comment]
@robmoore it can, yes. But that should probably be a different ticket.

**Comment by robmoore** [comment]
@josephholsten So I should create a ticket to fail if the chef-solo-search isn't found?

**Comment by scharissis** [comment]
Just for the benefit of those who find themselves here - I did manage to get around this and set up a single node replica set using chef-solo and chef-solo-search, as suggested. Simply add the new recipe:

```
"recipe[chef-solo-search]","recipe[mongodb::replicaset]"
```
