### ISSUE TITLE
Getting replication to work

### ISSUE THREAD

**Issue by sdarwin** [edelight/chef-mongodb#58]
Working on getting replication working with this recipe.   Sometimes it works for me, and sometimes not.    I happened upon this issue.

in libraries/mongodb.rb there is this line:

rs_connection = Mongo::ReplSetConnection.new( *old_members.collect{ |m| m.split(":") })

Notice the word "split".   It's spliting up the host and port which are divided by a : , and putting them into different arguments.     However the mongo ruby driver expects them all together, as in the following real example from their webpage:

Mongo::ReplSetConnection.new(['localhost:30000', 'localhost:30001'])

Notice there is no split there...    It therefore seems that this whole mess "*old_members.collect{ |m| m.split(":") }" should actually only be "old_members".     

Comments?

**Comment by jamesonjlee** [comment]
fix was merged
