### ISSUE TITLE
Duplicate Nodes in Config Object

### ISSUE THREAD

**Issue by ekristen** [edelight/chef-mongodb#61]
https://github.com/edelight/chef-mongodb/commit/8e330a79962e7633b916bcce201b44856a762297

This is causing duplicate nodes, essentially the new node to the replicaset is getting added twice, and the new replicaset fails to be added.

**Comment by ghost** [comment]
members << node unless members.include?(node)
I had the same issue.. I just commented that line

**Comment by ekristen** [comment]
I did that as well, but the issue I see now is that the roles aren't being updating the chef server, so the new node doesn't get included in the replicaset reconfig with it uncommented. So I am not sure what to do.

**Comment by dcrosta** [comment]
I think the right solution is to transform `members` into an array of hashes of known format, and add `node`'s entry to it if needed; the issue is that the search returns Node objects, but (at least in some cases) the one that represents the current node doesn't always equal the `node` object. I can take a stab at this soon, if no one else wants to.

**Comment by ekristen** [comment]
I was just thinking about this, why not just expand the members node search to include an OR name:currentnode then that way you get the objects directly from chef, because at run time it will be registered just not have the recipe officially leveraged against it.

Change

mongodb_cluster_name:#{replicaset['mongodb']['cluster_name']} AND \
       recipes:mongodb\:\:replicaset AND \
       mongodb_shard_name:#{replicaset['mongodb']['shard_name']} AND \
       chef_environment:#{replicaset.chef_environment}

to

mongodb_cluster_name:#{replicaset['mongodb']['cluster_name']} AND \
       recipes:mongodb\:\:replicaset AND \
       mongodb_shard_name:#{replicaset['mongodb']['shard_name']} AND \
       chef_environment:#{replicaset.chef_environment} OR \
       name:#{node.name}

**Comment by dcrosta** [comment]
@ekristen I like it. Want to submit a pull request?

**Comment by ekristen** [comment]
I will, I'm testing it first ;-)

**Comment by mbbernstein** [comment]
@ekristen 
I like your solution. 
Please make this pull request! 

Thanks, 
Michael

**Comment by ekristen** [comment]
Actually I found in testing that that solution does not work consistently.  Actually I found that the replicaset recipe does not work at all. I rewrote it.

https://github.com/ekristen/chef-mongodb

If you wouldn't mind checking out what I have done and seeing if it works and then I can create a pull request for updating the entire recipe.

**Comment by mbbernstein** [comment]
Hi Erik,

**I'm getting an error with the second node:**

```
[2012-10-17T15:23:24+00:00] INFO: Replicaset found. Connected to replicaset.
[2012-10-17T15:23:24+00:00] INFO: We are a replica set ... ensuring the primary is up and running
[2012-10-17T15:23:24+00:00] INFO: We are connected to the primary, continuing ...
[2012-10-17T15:23:24+00:00] INFO: [node[chef01]]
[2012-10-17T15:23:24+00:00] INFO: ["domU-12-31-38-01-84-EE.compute-1.internal"]
[2012-10-17T15:23:24+00:00] INFO: [node[chef01], node[chef02]]
[2012-10-17T15:23:24+00:00] INFO: Configuring replicaset with members domU-12-31-38-01-84-EE.compute-1.internal, domU-12-31-38-04-18-1F.compute-1.internal
[2012-10-17T15:23:24+00:00] INFO: Executing replSetReconfig
[2012-10-17T15:23:26+00:00] INFO: ruby_block[config_replicaset] called
[2012-10-17T15:23:26+00:00] INFO: Chef Run complete in 45.843059165 seconds
[2012-10-17T15:23:27+00:00] INFO: Running report handlers
[2012-10-17T15:23:27+00:00] INFO: Report handlers complete
```

**Connecting to the second node:**

```
ubuntu@domU-12-31-38-04-18-1F:~$ mongo
MongoDB shell version: 2.2.0
connecting to: test
Wed Oct 17 15:23:52 Error: couldn't connect to server 127.0.0.1:27017 src/mongo/shell/mongo.js:91
exception: connect failed
```

**After a little more time:**

```
ubuntu@domU-12-31-38-04-18-1F:~$ mongo
MongoDB shell version: 2.2.0
connecting to: test
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
> rs.status()
{
        "startupStatus" : 3,
        "info" : "run rs.initiate(...) if not yet done for the set",
        "errmsg" : "can't get local.system.replset config from self or any seed (EMPTYCONFIG)",
        "ok" : 0
}
> ^C
bye
ubuntu@domU-12-31-38-04-18-1F:~$
```

**In the first node:**

```
ubuntu@domU-12-31-38-01-84-EE:~$ mongo
MongoDB shell version: 2.2.0
connecting to: test
rs_default:PRIMARY> rs.status()
{
        "set" : "rs_default",
        "date" : ISODate("2012-10-17T15:28:08Z"),
        "myState" : 1,
        "members" : [
                {
                        "_id" : 0,
                        "name" : "domU-12-31-38-01-84-EE:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 633,
                        "optime" : Timestamp(1350487197000, 1),
                        "optimeDate" : ISODate("2012-10-17T15:19:57Z"),
                        "self" : true
                }
        ],
        "ok" : 1
}
rs_default:PRIMARY>
```

**Comment by ekristen** [comment]
I had that issue, but I thought I had corrected it. Let me run some tests real quick.

**Comment by ekristen** [comment]
Looks like it didn't successfully configure the second one, but configured the third just fine, which when it configured the third it configured the second as well. I'll have to do some more debugging.

**Comment by mbbernstein** [comment]
Yes, for me to..
The third and the fourth whent OK.

**Comment by ekristen** [comment]
Lets move this to an issue on my my fork. 

https://github.com/ekristen/chef-mongodb/issues/1
