### ISSUE TITLE
Adding third node results in "already initialized" error

### ISSUE THREAD

**Issue by ekristen** [edelight/chef-mongodb#63]
Creating the first node results in Cannot configure replicaset 'default_rs', no member nodes found

Second node results in -- config file saved locally, should come online in a few moments

Adding the third node results in a failure ---

{"errmsg"=>"couldn't initiate : member ip-10-170-86-60.us-west-1.compute.internal:27017 is already initiated", "ok"=>0.0}

From this error it sounds like the recipe is trying to initialize the third node as the primary in the replicate set instead of adding it to the existing??

**Comment by jayv** [comment]
having the exact same issue, 4 months since the report and no response :(

**Comment by ekristen** [comment]
I have fixed these issues with replicaset on my fork at https://github.com/ekristen/chef-mongodb, check it out let me know if it works, I haven't done a merge request yet because I haven't had enough people test and say it works for them.

**Comment by jayv** [comment]
Awesome work, that's exactly what I was about to write.

**Comment by tobami** [comment]
@ekristen so you have a fix for this?

**Comment by ekristen** [comment]
@tobami check out my repo linked above, test it out, let me know on my fork if it works for you or not, I've had mixed answers, but it works or is a lot closer to working then the replicaset script here.

**Comment by jamesonjlee** [comment]
merged in #91 that should fix this error.
