### ISSUE TITLE
Error on add 10gen repository

### ISSUE THREAD

**Issue by ashton** [edelight/chef-mongodb#66]
Hi, I'm using vagrant with chef solo, here are my run_list

Setting the run_list to ["recipe[apt]", "recipe[build-essential]", "recipe[apache2]", "recipe[apache2::mod_php5]", "recipe[php]", "recipe[php::module_mongodb]", "recipe[php::module_intl]", "recipe[mongodb]", "recipe[mysql]", "recipe[erlang]", "recipe[rabbitmq]"] from JSON
[2012-10-11T19:37:14+00:00] INFO: Run List is [recipe[apt], recipe[build-essential], recipe[apache2], recipe[apache2::mod_php5], recipe[php], recipe[php::module_mongodb], recipe[php::module_intl], **recipe[mongodb::10gen_repo]**, recipe[mysql], recipe[erlang], recipe[rabbitmq]]

And I'm getting this error: 

[2012-10-11T19:37:24+00:00] FATAL: NameError: Cannot find a resource for apt_repository on ubuntu version 12.04

**Comment by ashton** [comment]
I find out, that the problem is the version of apt recipe, the last stable version of this recipe only works with apt recipe until version 1.4.4. 

I can't figure out what is wrong, due to my lack of knowledge in chef.. But I presume that is a difference in apt_repository method since 1.4.4 version..

**Comment by shingara** [comment]
agree, not works with 1.9.0 too :(

**Comment by mbbernstein** [comment]
Upgrade your chef.

"Version 1.8.2+ of this cookbook requires Chef 10.16.4 or later."
Read this readme.
https://github.com/opscode-cookbooks/apt

**Comment by shingara** [comment]
you right, thanks.

**Comment by jamesonjlee** [comment]
chef issue, closing.
