### ISSUE TITLE
consider moving to three-digit semantic versioning in metadata.rb?

### ISSUE THREAD

**Issue by juliandunn** [edelight/chef-mongodb#76]
Best practice these days seems to be to use three-digit versions in metadata.rb for semantic versioning (http://semver.org/). Would you considering doing so?

**Comment by miketheman** [comment]
This is definitely something we would be interested in.

The current state is still a bit in flux - there a re many outstanding pulls and issues - we're deciding on the path to follow soon. A 3-digit version is definitely a good idea.
