### ISSUE TITLE
Move MongoDB Cookbook to its Own Repository

### ISSUE THREAD

**Issue by yfeldblum** [edelight/chef-mongodb#8]
Suggestion: move the MongoDB cookbook to its own repository, named e.g. `mongodb-cookbook` or `chef-mongodb`.

**Comment by tobami** [comment]
Can you please describe the reason or use case for having a separate repository for each cookbook?

**Comment by yfeldblum** [comment]
It's the same reason or use case for the existence of https://github.com/cookbooks and for how https://github.com/fnichol structures all his cookbooks. It makes the mongodb cookbook seem like it's its own project, like it's important in its own right. It also allows a set of issues and a wiki devoted specifically to the mongodb cookbook.

**Comment by tobami** [comment]
Ok. I can see how that can be useful in some cases, but for us it doesn't seem to bring much value but extra maintenance. Why have so many repos? Issues can be pegged to a particular cookbook through tags, for example, and the wiki can just be structured and written clearly.

We'll discuss it next week. Thanks for the suggestion.

**Comment by lackac** [comment]
Also, it would make the [knife-github-cookbooks](https://github.com/websterclay/knife-github-cookbooks) knife plugin work with this cookbook.

**Comment by yfeldblum** [comment]
In case the `knife-github-cookbooks` plugin does not work with this cookbook repository, you can already use the cookbook with [Librarian-Chef](https://github.com/applicationsonline/librarian).

```
# Cheffile
cookbook "mongodb",
  :git => "https://github.com/edelight/cookbooks"
```

Of course, since this is already [the `mongodb` cookbook on the Opscode Community Site](http://community.opscode.com/cookbooks/mongodb), you can just do this:

```
# Cheffile
site 'http://community.opscode.com/api/v1'

cookbook "mongodb"
```

**Comment by lackac** [comment]
I didn't know about Librarian-Chef, thanks for the tip.

**Comment by thekorn** [comment]
We startet discussing this issue today, thanks for bringing it up.
Our idea is to reorganize our git(hub) repository to use git submodules, such that each cookbook (or chef library) has its own repository but can be seen as one big repository at the same time.
Maybe this is the way the chef community should organize its cookbooks too, we plan to raise this topic for discussion at a later point.
Would this work for you too?

**Comment by yfeldblum** [comment]
It's great in terms of getting each individual cookbook into its own repository where it can stand on its own and be its own project.

It's an OK solution for a public cookbooks repository as a whole. It's not great because the submodule reference is not updated automatically and so needs to be updated separately. It's OK for working on a single application for vendoring its dependencies, but it doesn't work as well for a suite of unrelated applications (such as a collection of cookbooks) each of which has its own history.

**Comment by tobami** [comment]
Hi,

we just renamed the repo as "chef-cookbooks", as we had an issue with it having such a generic name.
We don't plan to separate it into individual cookbooks though. Opscode does cookbooks like this, and anyway once we have more than 4 or 5, it would clutter our account, which is _not_ primarily meant for Chef cookbooks ;-)

Besides, you said yourself that you can already use the repo with Librarian-Chef!
