### ISSUE TITLE
Seems to be a problem compiling mongodb.rb definition with chef-client 11.2.0

### ISSUE THREAD

**Issue by lanejlanej** [edelight/chef-mongodb#89]
[2013-02-08T15:26:32+00:00] WARN: Current  execute[apt-get-update]: /var/chef/cache/cookbooks/apt/recipes/default.rb:22:in `from_file'
# 
# Recipe Compile Error in /var/chef/cache/cookbooks/mongodb/recipes/default.rb
## ArgumentError

wrong number of arguments (1 for 2)
## Cookbook Trace:

  /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:144:in `block (2 levels) in from_file'
  /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:141:in`block in from_file'
  /var/chef/cache/cookbooks/mongodb/recipes/default.rb:38:in `from_file'
## Relevant File Content:

/var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:

137:      notifies :restart, "service[#{name}]"
138:    end
139:
140:    # service
141:    service name do
142:      supports :status => true, :restart => true
143:      action service_action
144>>     notifies service_notifies
145:      if !replicaset_name.nil?
146:        notifies :create, "ruby_block[config_replicaset]"
147:      end
148:      if type == "mongos"
149:        notifies :create, "ruby_block[config_sharding]", :immediately
150:      end
151:      if name == "mongodb"
152:        # we don't care about a running mongodb service in these cases, all we need is stopping it
153:        ignore_failure true

Works fine with 10.18.2

**Comment by gnufied** [comment]
I get same error.

**Comment by RSO** [comment]
Me too!

**Comment by beingmattlevy** [comment]
I am getting multiple errors from this and chef 11.2.0

**Comment by untoldone** [comment]
This seems to be caused by a breaking change to chef introduced between chef 10 and 11 (http://docs.opscode.com/breaking_changes_chef_11.html#single-notifies-for-notification). I fixed this by replacing line 144 of definitions/mongodb.rb with the following

```
service_notifies.each do |service_notify|
  notifies :run, service_notify
end
```

As a side note, as someone evaluating chef: the long history of breaking changes between every major version of chef definitely makes me pause...

**Comment by Parad0X** [comment]
Could you create a new tag please? Latest version from opscode is 0.11.0 which doesn't work with chef 11.

**Comment by davekonopka** [comment]
:+1: for a new version number tag. Community cookbook is unusable with Chef 11.

**Comment by andrewryno** [comment]
:thumbsup: for new tag as well. Applying that same patch gets through that error, though.

**Comment by untoldone** [comment]
As I recall -- the patch I submitted made the cookbook work in both 10 and 11? Honestly not using the cookbook anymore and the patch was really just 2-3 lines. Hopefully someone can take on anything else needed here?

**Comment by andrewryno** [comment]
Yeah the patch worked for me. I'm getting other errors though (in #86).

**Comment by jamesonjlee** [comment]
considering this fixed. the other issue sited by #86 (due to init.d/service) is another matter...
