### ISSUE TITLE
Shards and Configserver Services missing params

### ISSUE THREAD

**Issue by zmsmith** [edelight/chef-mongodb#9]
Maybe I'm missing something here, but here are the service commands:

configserver:

``` bash
$ sudo service configserver
** Running configserver (/usr/bin/mongod  --port 27017 --dbpath /var/lib/mongodb --logpath /var/log/mongodb/configserver.log)
```

shard:

``` bash
$ sudo service configserver
** Running shard (/usr/bin/mongod  --port 27017 --dbpath /var/lib/mongodb --logpath /var/log/mongodb/shard.log)
```

Don't these need --configsrv and --shardsrv?

**Comment by thekorn** [comment]
Hi Zach,
yes, theoretically you are right it seems like these options are missing. However right now these options only change the default port, and since we define the port ourselves anyway, adding this option makes no sense.
If these options do something more useful in later versions of mongodb I'm happy to add them to the arguments of the configserver and shard service.

Markus

**Comment by zmsmith** [comment]
Got it. Thanks!

**Comment by sdarwin** [comment]
Here are some reasons to keep --configsvr and --shardsvr.   
1.  There is some minor error checking done, in the mongo code, based on these values.
2.  For clarity, and for consistency with the official mongo docs.   I was also confused by the missing flags, until I found this "issue" doc here..   If the mongo docs are all going to stay on point that those flags are supposed to be there, then the cookbook should keep them also.
3.  The mongo source code may eventually add more error checking and/or functionality related to these flags.
4.  You can apparently set the port and the flag, both.    If you choose to set the port, it will override the default.  If you don't set the port, then the default will be used.     This sort of arrangement would ideally be mimicked in the chef recipe also.

However, based on a cursory scan of the chef recipes, I am slightly doubtful that the flags --configsvr and --shardsvr (which have been disabled) can instantly be turned on.    The logic there may need some tweaking.
