### ISSUE TITLE
mongodb_instance on default recipe breaks Ubuntu 12.04

### ISSUE THREAD

**Issue by gamafranco** [edelight/chef-mongodb#92]
The mongodb_instance code on the default recipe breaks ubuntu.

Why are we running the configuration, if the default ubuntu package already has start and stop scripts?

Is it possible to make this part optional?

Thanks.

**Comment by arturhoo** [comment]
Please excuse my lack of chef knowledge, but I would also like to know why `/etc/defaults` is used to hold the configuration parameters instead of the usual `/etc/mongodb.conf`, and why doesn't the cookbook use the default init.d script shipped with the `mongodb-10gen` package.

**Comment by stanhu** [comment]
Yes, why isn't the cookbook creating a mongodb.conf from a template?  I would have expected all the configuration parameters to have been stored there, but instead they are buried in command-line arguments in the non-obvious /etc/defaults.
